mysociety/whatdotheyknow-theme

- lib/views/help/unhappy.html.erb
> Replace broken link to the ICO website

- lib/views/help/unhappy.html.erb
Fixes https://github.com/mysociety/alaveteli/issues/2222
> Remove pledgebank mention

- lib/views/request/_next_actions.html.erb
'Help me investigate' was mothballed in December, so we should remove our link to it.
Fixes https://github.com/mysociety/alaveteli/issues/2221
> Remove helpmeinvestigate mention

- lib/views/general/_responsive_footer.html.erb
> [#200] Correct Facebook URL

- assets/stylesheets/responsive/custom.scss
- lib/views/general/_before_body_end.html.erb
- lib/views/general/_locale_switcher.html.erb
This moves the locale switcher to the right of the logo, part of the much bigger https://github.com/mysociety/alaveteli/issues/1525 
The final commit needs some dev work, I've left a line comment. 
Screenshots:
> Move locale switcher

- assets/stylesheets/responsive/custom.scss
- lib/views/general/_frontpage_bodies_list.html.erb
- lib/views/general/_frontpage_requests_list.html.erb
This reorganises and redesigns the 'recently requested' section of the homepage, part of the bigger https://github.com/mysociety/alaveteli/issues/1525 ticket
> Homepage redesign recently requested

- assets/stylesheets/responsive/custom.scss
- lib/views/general/_frontpage_hero.html.erb
- lib/views/general/_frontpage_how_it_works.html.erb
- lib/views/general/_responsive_header.html.erb
This adds the 'how it works' section to the new homepage
> Homepage how it works

- assets/stylesheets/responsive/custom.scss
> Improve logged in experience

- assets/stylesheets/responsive/custom.scss
- lib/views/general/_frontpage_hero.html.erb
- lib/views/general/_frontpage_how_it_works.html.erb
- lib/views/general/_frontpage_requests_list.html.erb
This changes the display code for buttons, they are now more consistent with our house style
> Redesign buttons

- lib/views/general/_responsive_footer.html.erb
> [#204] Add API link to the footer

- assets/stylesheets/responsive/custom.scss
Improved spacing, typography and button layout
> Sidebars now look like the reference design

- assets/stylesheets/responsive/custom.scss
Blog styling is much clearer.
Added WordPress styles to make sure images and other styles aren't looking messy
(show hover styles on the first post title)
> improve blog styling

- assets/stylesheets/responsive/custom.scss
(sidebar is tidied in a separate PR #220)
> Visual hierarchy of buttons now much improved on Authority page

- assets/stylesheets/responsive/custom.scss
- lib/views/general/_frontpage_bodies_list.html.erb
Stops a couple of cosmetic bugs with buttons mainly affecting the homepage
> Homepage buttons bug fix

- assets/stylesheets/responsive/custom.scss
> Style pagination

- assets/stylesheets/responsive/custom.scss
> visual tweak to correspondence thread, part of #218

- assets/stylesheets/responsive/custom.scss
> pagination now behaves nicer in longer lists and smaller screens

- assets/stylesheets/responsive/_print_style.scss
- assets/stylesheets/responsive/custom.scss
- assets/stylesheets/responsive/print.scss
- lib/views/general/_responsive_header.html.erb
fixes #223
Pages should now hide all necessary elements when printed
No width restrictions
Very readable
> New print.css

- assets/stylesheets/responsive/custom.scss
> corrected colour of error message background. Was green, is now red.

- lib/views/help/privacy.cy.html.erb
- lib/views/help/privacy.html.erb
> Add some information about our webserver logs.

- spec/model_patches_spec.rb
Depends on https://github.com/mysociety/alaveteli/pull/2726
> Upgrade spec syntax for rspec 3.

- lib/views/help/credits.html.erb
Fixes #286 
Been sat there a while and didn't want to let this go to waste.
Could do with confirming whether there were any more original funders other than the Joseph Rowntree Trust.
> [#286] Update credits page

- lib/views/help/unhappy.html.erb
Merge in https://github.com/mysociety/alaveteli/issues/2941
https://github.com/mysociety/alaveteli/pull/3010
> [#2457] Add link to ask the eu

- lib/model_patches.rb
- lib/school_late_calculator.rb
- spec/model_patches_spec.rb
- spec/school_late_calculator_spec.rb
Fixes mysociety/alaveteli#625
Requires https://github.com/mysociety/alaveteli/pull/2963
> [#625] Extract school logic

- lib/views/request/_request_sent.html.erb
> [#298] Request Made Conversion Tracking

- assets/stylesheets/responsive/custom.scss
- lib/views/request/show.html.erb
> add an advertisement for AskTheEU to request pages

- lib/views/general/_frontpage_bodies_list.html.erb
- lib/views/request/select_authority.html.erb
- lib/views/request/show.html.erb
Better tracking in Analytics for https://github.com/mysociety/alaveteli-experiments/issues/54.
> Add utm tracking params to AskTheEU promo links

- lib/views/general/_responsive_footer.html.erb
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/327
> [#327] Fix typo

- assets/stylesheets/responsive/custom.scss
- lib/views/request/_request_sent.html.erb
- lib/views/request/describe_notices/_successful.html.erb
Update
----------
To do 
Part of #309
Here's how the messages look now
A note for the future, the way the notices and messages are put together in Alaveteli is messy and quite hard to follow - I'll open a ticket to refactor these
> Add donate prompts

- assets/stylesheets/responsive/custom.scss
- lib/views/request/_sidebar.html.erb
Part of #309 
✋ Needs deployment plan.
> Add donate cta to request sidebar

- assets/stylesheets/responsive/_mysoc_footer.scss
We can then set a long expiration time.
> Use asset-pipeline URLs so that we get timestamping on image paths.

- lib/views/request/select_authority.html.erb
Requires a907ddcb5f9102d778b8dff5108cf4faca5ba42b.
> Move javascript to end of body tag.

- lib/alavetelitheme.rb
- lib/analytics_event.rb
- lib/views/request/_next_actions.html.erb
- lib/views/request/_next_share_actions.html.erb
- lib/views/request/_sidebar.html.erb
Part of https://github.com/mysociety/alaveteli/issues/3394
Adds event tracking to Write To Them link
> [#3394] act writetothem

- lib/views/request/show.html.erb
Requires https://github.com/mysociety/alaveteli/pull/3392
> Add new request as Google Analytics event.

- lib/views/request/_sidebar.html.erb
> Don't show sidebar donation box with the 'request has been sent' panel

- lib/views/help/privacy.html.erb
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/339
> [#339] Make foi-register note past tense

- assets/stylesheets/responsive/custom.scss
- lib/views/help/_sidebar.cy.html.erb
- lib/views/help/_sidebar.html.erb
- lib/views/help/about.cy.html.erb
- lib/views/help/about.html.erb
- lib/views/help/alaveteli.html.erb
- lib/views/help/api.html.erb
- lib/views/help/contact.cy.html.erb
- lib/views/help/contact.html.erb
- lib/views/help/credits.html.erb
- lib/views/help/officers.cy.html.erb
- lib/views/help/officers.html.erb
- lib/views/help/privacy.cy.html.erb
- lib/views/help/privacy.html.erb
- lib/views/help/requesting.cy.html.erb
- lib/views/help/requesting.html.erb
- lib/views/help/unhappy.html.erb
> 316 help sidebar

- lib/views/general/_popup_banner.html.erb
Christmas/New Year donation banner
Connects to #284
> Add donate banner

- lib/model_patches.rb
- spec/model_patches_spec.rb
See ticket for full description - the initial query, being `InfoRequest` rather than `User`-centric can pull back multiple records per user if they have made more than one request in the qualifying period for the survey.
As noted in the code comment, this is a cheap fix - it probably would have been better to fix the initial query, but at least better than editing the send loop to query the db each time to check whether the user has a 'sent' event.
Fixes #356
> Prevent the survey from being sent multiple times

- lib/views/request/show.html.erb
mysociety/alaveteli#3656 refactors this view considerably to improve the
code around updating request statuses and to add a pro version of the page.
This brings WDTK-theme in line with those changes.
> Update request/show.html.erb view to match refactoring in Alaveteli Pro

- lib/views/followups/_followup.html.erb
Matching PR for mysociety/alaveteli#3659
> Update new followup page title to match AP

- lib/views/request/show.html.erb
Closes https://github.com/mysociety/alaveteli-professional/issues/130
> [Pro] Don't show pro users AskTheEU ad on request page.

- lib/views/general/_popup_banner.html.erb
Deadline for applications is 20th March 2017, hence the date
conditional.
Fixes #383
> [#383] Add banner promoting call for volunteers

- lib/views/help/contact.html.erb
For mysociety/alaveteli-professional#160
> [Pro] Update text on help page to not reference volunteers

- lib/views/general/_popup_banner.html.erb
> [#393] Add banner about last day to make request before election

- lib/views/general/_orglink.html.erb
No longer used after core commit d80e0ec0bc2bf81a0714cd44750da46faad44c06
> Remove obsolete template

- app/assets/stylesheets/responsive/_help_layout.scss
- lib/config/wdtk-routes.rb
- lib/controller_patches.rb
- lib/views/help/_sidebar.html.erb
- lib/views/help/about.html.erb
- lib/views/help/api.html.erb
- lib/views/help/beginners.html.erb
- lib/views/help/complaints.html.erb
- lib/views/help/credits.html.erb
- lib/views/help/house_rules.html.erb
- lib/views/help/how.html.erb
- lib/views/help/officers.html.erb
- lib/views/help/principles.html.erb
- lib/views/help/privacy.html.erb
- lib/views/help/requesting.html.erb
- lib/views/help/volunteers.html.erb
> New help page texts

- lib/views/alaveteli_pro/pages/_legal.html.erb
- lib/views/general/_responsive_footer.html.erb
Work on https://github.com/mysociety/alaveteli-professional/issues/346
Requires https://github.com/mysociety/alaveteli/pull/4324
> [pro#346] T&Cs for Pro

- app/assets/stylesheets/responsive/custom.scss
- lib/views/request/_next_actions.html.erb
- lib/views/request/show.html.erb
Corresponding PR to https://github.com/mysociety/alaveteli/tree/issues/4342-performance-improvement--sprites.
Ensures the custom templates here don't break
> Alaveteli issues/4342 performance improvement  sprites

- app/assets/stylesheets/responsive/_mixins.scss
- app/assets/stylesheets/responsive/_print_style.scss
- app/assets/stylesheets/responsive/custom.scss
- lib/views/general/_responsive_header.html.erb
- lib/views/request/_next_actions.html.erb
- lib/views/request/show.html.erb
Some small fixes and changes to improve front end performance of the site.
Corresponding with https://github.com/mysociety/alaveteli/pull/4355
> Alaveteli issues/4342 performance improvement

- lib/views/alaveteli_pro/account_request/_account_request_form.html.erb
- lib/views/alaveteli_pro/account_request/index.html.erb
Requires https://github.com/mysociety/alaveteli/pull/4406
> Move custom account request pages from core

- lib/helper_patches.rb
- lib/helpers/donation_helper.rb
- lib/views/request/_request_sent.html.erb
- lib/views/request/_sidebar.html.erb
- lib/views/request/describe_notices/_successful.html.erb
- spec/donation_helper_spec.rb
Closes https://github.com/mysociety/alaveteli-professional/issues/137
> [pro#137] Hide donation buttons from pros

- lib/views/public_body_change_requests/new.html.erb
Had 5 minutes so just got this done.
Fixes https://github.com/mysociety/alaveteli/issues/4486.
> [core#4486] Add several authorities

- app/assets/stylesheets/responsive/custom.scss
Part of https://github.com/mysociety/alaveteli/issues/4085
Requires https://github.com/mysociety/alaveteli/pull/4219
> WIP: Tweak to styling for collapsed correspondence

- lib/views/help/privacy.html.erb
We should probably think about what to do about getting a Welsh translation for this.
> Add new privacy page text

- lib/views/help/privacy.html.erb
> [#469] Updates to the privacy page

- lib/views/help/house_rules.html.erb
Make heeding our advice on responsible and effective requests a house
rule.
This has come about from users interested in Pro asking about making
requests to all local authorities.
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/474.
> [#474] Add new house rule

- lib/views/help/privacy.html.erb
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/469
> [#469] Clarify our official charity name

- lib/views/general/_responsive_footer.html.erb
mySociety is the project, mySociety Ltd is a Ltd company wholly owned by
UKCOD.
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/480
> [#480] Clarify wording of footer legal statement

- lib/views/general/_responsive_footer.html.erb
We don't mention /pro elsewhere, so this is a good place to start.
> Add Journalist? pro upsell to footer

- app/assets/stylesheets/responsive/custom.scss
A couple of tweaks that are required due to changes in https://github.com/mysociety/alaveteli/pull/4810
> Tweaks to user menu related to changes in alaveteli/issues/4780

- app/assets/stylesheets/responsive/custom.scss
> Add styles for Alaveteli Pro sidebar navigation release

- lib/views/help/officers.html.erb
The PDF has now moved to the new URL.
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/506.
> [#506] Fix broken URL

- lib/views/help/house_rules.html.erb
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/493.
> [#493] Add House Rule for ban evasion

- lib/views/help/privacy.html.erb
* Extend from 2 weeks to 4 weeks
* Add discretionary period after engagement with ICO commences
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/500
> [#500] Update Data Retention Policy

- app/assets/stylesheets/responsive/custom.scss
- lib/views/general/_responsive_header.html.erb
Reapplies customisations and changes coming from core (https://github.com/mysociety/alaveteli/pull/4878)
Before
After
> Preparation for header changes from core

- lib/views/help/about.html.erb
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/517
> [#517] Fix broken ICO URL

- lib/views/alaveteli_pro/pages/_legal.html.erb
- lib/views/help/about.html.erb
> [#520] Include company name in postal address

- lib/views/request/_select_authority_help.html.erb
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/558
* Adds missing URLs from placeholders
* Adds missing translation wrappers
Missed in https://github.com/mysociety/whatdotheyknow-theme/pull/545.
> [#558] Fix broken links on select authority page

- lib/public_body_questions.rb
Would be good to get this in before https://github.com/mysociety/alaveteli/issues/4902 in case 3rd party themes are updated incorrectly.
Fixes #571
> [#571] Fix database rake tasks

- lib/views/help/officers.html.erb
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/609.
> Add section on classifications for FOI officers

- app/assets/stylesheets/responsive/custom.scss
Connected to https://github.com/mysociety/alaveteli/pull/5428
Fixes #613
> [#5419] Update button styles

- lib/views/help/officers.html.erb
- lib/views/help/privacy.html.erb
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/606
> [#606] Update remote link

- lib/model_patches.rb
Required by mysociety/alaveteli#3970
~~Overrides `RequestMailer.alert_new_response_reminders` using `alias_method` (and repeating the original code/adding the extra line manually) rather than `alias_method_chain`~~
Patches RequestMailer using `include`/`prepend` with survey methods without using the old `alias_method_chain` and without duplicating code from Alaveteli core.
`alias_method_chain` (deprecated in Rails 5.0) has been removed in Rails 5.1
> [Rails 5.1] Stop using alias_method_chain

- app/assets/javascripts/tests.js
- lib/views/request/show.html.erb
Removes the experiment-specific code.
Fixes https://github.com/mysociety/alaveteli-experiments/issues/117
> [experiments#117] Remove donate button experiment

- lib/views/help/unhappy.html.erb
- lib/views/request_mailer/overdue_alert.text.erb
- lib/views/request_mailer/very_overdue_alert.text.erb
> Be clearer that a request that hasn't been responded to can go to the ICO

- lib/views/help/requesting.html.erb
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/655
> [#655] Minor grammar change

- lib/views/request/show.html.erb
From: https://github.com/mysociety/alaveteli/pull/5641
> Reconcile with changes to request header

- lib/views/general/_responsive_footer.html.erb
Small but important tweak to the legal wording in the footer, now that the company names have changed.
> Update company details in footer

- lib/views/help/about.html.erb
- lib/views/help/complaints.html.erb
- lib/views/help/officers.html.erb
- lib/views/help/privacy.html.erb
I think this PR captures all references to the old company name, and replaces them with mySociety.
> Company name change

- lib/views/help/privacy.html.erb
Completes #685, amends previous paragraph with the fact that the research policy is complete and viewable.
> Update privacy policy to reflect research policy

- lib/controller_patches.rb
- lib/model_patches.rb
Little bit of cleanup while reviewing code in relation to https://github.com/mysociety/whatdotheyknow-theme/issues/580.
> Minor cleanup of model and controller patches

- lib/config/wdtk-routes.rb
- lib/controller_patches.rb
- lib/views/help/_sidebar.html.erb
- lib/views/help/ico_officers.html.erb
Hi @gbp 
Added ICO offers help page.
Let me know if it's ok.
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/729
> [#729] Add ICO officers help page

- config/refusal_advice/actions.yml.erb
- lib/views/help/unhappy.html.erb
Fixes https://github.com/mysociety/alaveteli/issues/6236
Fixes https://github.com/mysociety/alaveteli/issues/6235
Requires https://github.com/mysociety/alaveteli/pull/6258 to show unfold arrows
> Polish help unhappy

- config/refusal_advice/actions.yml.erb
Closes https://github.com/mysociety/alaveteli/issues/6244
> Change final statement of requests wizard to work without suggested actions

- app/assets/stylesheets/responsive/custom.scss
- lib/views/help/unhappy.html.erb
Contains code to work alongside https://github.com/mysociety/alaveteli/pull/6306 for WDTK's content
> Hide wizard content from non js users

- lib/model_patches.rb
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/873
> Add UKAEA invalid reply address

- lib/views/help/credits.html.erb
Link to funding page as per https://github.com/mysociety/whatdotheyknow-theme/issues/434#issuecomment-990142372
> Add more information on mySociety funding

- lib/views/help/privacy.html.erb
Clarify how we assess removal of information.
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/876.
> [#876] Add link to legitimate interests basis

- lib/views/help/privacy.html.erb
> Add "WhatDoTheyKnow and young people" privacy section

- config/refusal_advice/section_43.yml.erb
The PDF URL now 404s, so replace with the nicer HTTP URL and update the
text that we're quoting to reflect the slightly tweaked phrasing.
Hat tip to @mvl22 for the updated URL.
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/1110.
> [#1110] Update Section 43 Third Party advice

- lib/views/general/_nav_items.html.erb
The pro site is lovely! This adds a link so people can see it.
> Add Pro page to main navigation

- lib/views/help/credits.html.erb
Wrap up from annual volunteer audit – sorry this part was a bit late;
was a missing step on the checklist!
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/1189
> Add William to credits

- app/assets/stylesheets/responsive/custom.scss
- lib/alavetelitheme.rb
- lib/controller_patches.rb
- lib/mailer_patches.rb
- lib/views/contact_mailer/volunteer_message.text.erb
- lib/views/help/_contact_volunteer_form.html.erb
- lib/views/help/contact.html.erb
- lib/volunteer_contact_form.rb
Requires core changes: https://github.com/mysociety/alaveteli/pull/7063
Fixes: https://github.com/mysociety/whatdotheyknow-theme/issues/1179
Styling issues outside the form (list bullets) has been left as this effects the other sections on this page.
> Add volunteer contact form

- lib/views/help/volunteers.html.erb
> Update the Get Involved help page

- lib/views/public_body/_more_info.html.erb
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/1267.
> [#1267] Add special link for NI charities

- lib/views/general/_responsive_footer.html.erb
Also fixes hash style.
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/934.
> Convey longevity of WDTK

- lib/views/help/how.html.erb
- lib/views/help/unhappy.html.erb
Make it clearer that we don't check the information on the site.
Clarifies help text.
Helps users.
See above.
N/A
See above. See also: https://wdtkwiki.mysociety.org/wiki/Draft_legal_notice_for_the_site
> we don't check the information on the site

- lib/views/help/requesting.html.erb
Thanks to @mdeuk for the phrasing. I merely copy and pasted it here.
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/786.
> [#786] Pro is no longer forthcoming

- lib/views/help/about.html.erb
- lib/views/help/glossary.html.erb
- lib/views/help/privacy.html.erb
- lib/views/help/requesting.html.erb
Fixing typos, adding "GitHub" to Glossary.
See above.
See above.
See above.
N/A,
N/A.
> general improvements to help text

- lib/views/help/_contact_volunteer_form.html.erb
Connected to #1473 
Update honey pot form field
Honey pot form field isn't being populated by spammers, not sure why but this seems to work on the other forms. Lets try reordering the fields and change how the form field is hidden from real users.
> [#1473] Update honey pot form field

- lib/volunteer_contact_form.rb
Connected to #1473
Improve volunteer form spam detection
We're getting lots of spam on the volunteer form. Most of the messages have the same text in `why`, `experience` and `anything_else` fields. Lets detect this and fake the message sent flash so spam bots don't change their behaviour.
> Improve volunteer form spam detection

- lib/views/public_body/_more_info.html.erb
Reverts mysociety/whatdotheyknow-theme#1589
> Revert "New ways to link to external sites from authority pages and minor changes to help text "

- lib/views/help/officers.html.erb
Use application values so that configuration changes do not go out of sync with explanatory text.
Requires https://github.com/mysociety/alaveteli/pull/7563
> Dynamically render anti-spam calculations

- lib/model_patches.rb
> Disable user messages outside 9-5

- app/assets/stylesheets/responsive/custom.scss
- lib/views/general/_frontpage_blog.html.erb
- lib/views/general/_frontpage_extra.html.erb
- lib/views/request/_sidebar.html.erb
See: https://github.com/mysociety/alaveteli/pull/7645
> Reconcile with core

- lib/config/wdtk-routes.rb
- lib/controller_patches.rb
- lib/views/help/_sidebar.html.erb
- lib/views/help/environmental_information.html.erb
- lib/views/help/glossary.html.erb
#1493 
Adds a help page on Environmental Information that can be expanded or improved later. 
EIR is awesome, so we really should tell people about it. Also #IssueZero
I wrote this whilst I was bored waiting for my scripts to run this afternoon. It was tested via a quite heavily modified version of the WDTK theme, so perhaps check to make sure nothing odd has slipped through...
> 1493 provide a good explanation of what environmental information is

- lib/views/help/environmental_information.html.erb
Fixing spelling
n/a
Fixes typos
Things were spelt incorrectly
n/a
n/a
The rest of it seems fine 🙂
> Fix typos in environmental_information.html.erb

- lib/views/help/officers.html.erb
Update the request count in the FOI officer help page
#1658 
Updates the number of requests
The figure was very out of date
n/a
n/a
n/a
> Update the request count in the FOI officer help page

- lib/views/help/_contact_volunteer_form.html.erb
- lib/volunteer_contact_form.rb
Combat spam on the volunteer contact form.
> Add check of external links on volunteer contact form

- lib/views/help/_contact_volunteer_form.html.erb
- lib/volunteer_contact_form.rb
Ensures only contact volunteer form validator is used on the volunteer form.
Fixes #1674
> Fix issue rendering contact forms

- lib/views/help/credits.html.erb
None 
Add a more prominent credit to recognise Richard's volunteering. 
A nice change to make on his departure from the volunteer team
> Update credits.html.erb, add credit for Richard Taylor

- lib/views/help/environmental_information.html.erb
Fixes #1704 
- Adds guidance links
- Adds emojis
Makes it easier for users to fin information about their rights
> Improving the environmental information page by adding links to guidance

- lib/views/followups/_followup.html.erb
Reconcile with core
See: https://github.com/mysociety/alaveteli/pull/7736
> [core#285] Allow user to edit their name

- app/assets/stylesheets/responsive/custom.scss
- lib/views/general/_frontpage_extra.html.erb
- lib/views/general/_how_do_we_help.html.erb
- lib/views/general/_patterns_of_use.html.erb
- lib/views/general/_what_is_foi.html.erb
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/1710
Adds some homepage sections around:
* What is FOI
* Why is FOI useful
* How does WDTK help
We don't really explain how a newcomer to FOI can use it.
Stole the CSS from the "articles" section. I think we could make more generic components here, but it'll do for now.
> [#1710] FOI is awesome

- app/assets/stylesheets/responsive/custom.scss
The closed correspondence notice on the request officer upload form should match the match the sign in reason notices.
Connect to https://github.com/mysociety/alaveteli/pull/7891
> Update styles for closed correspondence

- lib/views/general/_frontpage_videos.html.erb
> Add campaigns & data visualisation video

- lib/model_patches.rb
- spec/public_body_spec.rb
Requires https://github.com/mysociety/alaveteli/pull/7836
> Add UK-specific excluded calculated homepage domains

- lib/volunteer_contact_form.rb
Replace with the generic abstraction.
Requires https://github.com/mysociety/alaveteli/pull/7967.
> Use MailHelper#case_reference for Volunteer form

- lib/views/help/house_rules.html.erb
Provides guidance on information requests about family members.
See above.
See above.
N/A.
N/A.
See above.
> Guidance on information requests about family members

- lib/views/general/_frontpage_hero.html.erb
Goes back to normal at 1,001,000.
> Going all out for the 1 million

- lib/views/general/_responsive_header.html.erb
Missed in #1818
Update pennant link and alt text
> Update pennant link and alt text

- lib/views/general/_how_do_we_help.html.erb
over one million requests now - wording change
See above.
See above.
See above.
See above.
See above.
> over one million

- lib/excel_analyzer.rb
Fixes #1835
Fixes the spelling.
The spelling was wrong.
n/a
n/a
n/a
> Fix spelling

- lib/views/request/_request_sent.html.erb
- lib/views/request/describe_notices/_successful.html.erb
Replace Twitter with X and related wording.
> Update social call to actions

- lib/model_patches.rb
Fixes #1852 
Adds a no-reply
They use a no reply
n/a
n/a
n/a
> Add Tandridge no-reply

- app/assets/stylesheets/responsive/custom.scss
- lib/alavetelitheme.rb
- lib/topic_pages.rb
- lib/views/general/_nav_items.html.erb
- lib/views/request/_tabs.html.erb
https://github.com/mysociety/alaveteli/issues/7981
1. Add subnav styling
2. Add feature flag for topic pages
Needed for https://github.com/mysociety/alaveteli/pull/8206
> Topic pages

- lib/views/general/_default_footer.text.erb
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/1867.
> [#1867] Link to service-specific donate page

- lib/views/public_body/_more_info.html.erb
Add a search for mentions of the authority in parliament.
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/1332
> Add link to TheyWorkForYou from body sidebar

- lib/excel_analyzer.rb
- lib/views/excel_analyzer_notifier/report.text.erb
Fixes #1870
Add admin request link to email notifications
> [ExcelAnalyzer] Add admin request link to email notifications

- lib/excel_analyzer.rb
Fixes: https://github.com/mysociety/whatdotheyknow-private/issues/308
> Update ExcelAnalyzer report emails destination

- Rakefile
- lib/mailer_patches.rb
- lib/tasks/alavetelitheme_tasks.rake
- lib/views/alaveteli_pro/subscription_mailer/notify_price_increase.text.erb
> Add Pro subscription price increase mailer

- lib/views/help/how.html.erb
Fixes #1305
Adds additional help text re professional advice and medical information.
To reduce the risk that people rely inappropriately on information that appears on the site.
N/A
N/A
N/A
> Update how.html.erb (professional advice and medical information)

- .github/workflows/ci.yml
- lib/alavetelitheme.rb
- lib/authority_only_response_gatekeeper.rb
- lib/model_patches.rb
- lib/raw_email_usage.rb
For future analyst. This will track web/sidekiq and command like when we
index Xapian.
> Track calls to RawEmail#data

- lib/views/help/complaints.html.erb
- lib/views/help/house_rules.html.erb
- lib/views/help/removing_information.html.erb
This makes some initial additions to help pages with reference to the Online Safety Act. Further, more detailed, updates may be needed in due course.
> Make some initial update to reference the Online Safety Act

- .typos.toml
- app/assets/stylesheets/responsive/_mixins.scss
- app/assets/stylesheets/responsive/custom.scss
- lib/views/general/_frontpage_articles.html.erb
- lib/views/general/_frontpage_blog.html.erb
- lib/views/general/_how_do_we_help.html.erb
- lib/views/general/_patterns_of_use.html.erb
- lib/views/general/_what_is_foi.html.erb
- lib/views/help/about_foisa.html.erb
- lib/views/help/privacy.html.erb
- lib/volunteer_contact_form.rb
Found using https://github.com/crate-ci/typos
Also done in core https://github.com/mysociety/alaveteli/pull/8728
> Correct spelling mistakes

- lib/model_patches.rb
- spec/model_patches_spec.rb
Reg 2 of The Freedom of Information (Time for Compliance with Request)
Regulations 2010 indicates that similar treatment should also apply to
"the proprietor of an Academy"
Fixes #2016
> [#2016] Academy late calculator
