mysociety/whatdotheyknow-theme

- assets/stylesheets/responsive/custom.scss
- lib/views/help/_sidebar.cy.html.erb
- lib/views/help/_sidebar.html.erb
This adds a more traditional layout to the help pages, with a sidebar, and tidies up the typography
> Tidy up help pages

- assets/stylesheets/responsive/custom.scss
The follower count border is now flush
The margin making the spacing uneven is gone
> fix a couple of bugs introduced with various merges, and typeface change

- lib/views/help/about.cy.html.erb
- lib/views/help/about.html.erb
- lib/views/help/api.html.erb
- lib/views/help/credits.html.erb
- lib/views/help/officers.cy.html.erb
- lib/views/help/officers.html.erb
- lib/views/help/privacy.cy.html.erb
- lib/views/help/privacy.html.erb
- lib/views/help/requesting.cy.html.erb
- lib/views/help/requesting.html.erb
Fixes most of the broken links - including the matching links (but not the link text) on the Welsh pages.
The trickier problem posed by the archiving of http://www.justice.gov.uk/information-access-rights/foi-guidance-for-practitioners/procedural-guidance/foi-what-constitutes link is not addressed here but has been documented in #270 
Fixes #267
Fixes #268
> Fix broken links in help pages

- lib/views/help/about.html.erb
Changes the line in the help/about page from a hardcoded - and currently out of date - number to a calculation on the actual user count, rounded to the nearest thousand.
While not relevant to WDTK, the commit message contains a warning about what happens if you have fewer than 1000 users when using this code change (my dev box has 11, which rounded down to 0).
There's probably something cleverer we could do to make sure we're rounding the number appropriately (possibly as a class method on User?) but it's not needed here.
Fixes #266
> Calculate the number of registered users on the about page

- lib/views/help/privacy.html.erb
Removed the link to the now-archived http://www.justice.gov.uk/information-access-rights/foi-guidance-for-practitioners/procedural-guidance/foi-what-constitutes, leaving just the original text.
Closes #270
> Removed link to archived justice.gov.uk page

- lib/config/wdtk-routes.rb
- lib/controller_patches.rb
- lib/views/outgoing_mailer/_followup_footer.text.erb
Link added to https://ico.org.uk/media/for-organisations/documents/how-to-disclose-information-safely-removing-personal-data-from-information-requests-and-datasets/1432979/how-to-disclose-information-safely.pdf
Have added a WDTK route for the pdf as the direct link is too long for a plaintext email and wraps awkwardly
Fixes #279
> Link to ICO guidance pdf in outgoing email

- lib/views/followups/_followup.html.erb
- lib/views/request/show.html.erb
- lib/views/request_mailer/overdue_alert.text.erb
- lib/views/request_mailer/very_overdue_alert.text.erb
Override views relying on deprecated `PublicBody#is_school?`
https://github.com/mysociety/alaveteli/issues/625
> [#625] School logic views

- lib/views/request/_sidebar.html.erb
Needs the corresponding PR for alaveteli too, so that `current_user` is a
helper method available to views.
Closes mysociety/alaveteli-professional#137
> Don't show the donate banner to pros.

- lib/model_patches.rb
The original hack fails in Rails 4.1 with a NoMethodError:
UserInfoRequestSentAlert._validate_callbacks[0].options[:in] << 'survey_1'
NoMethodError: undefined method `[]' for #<ActiveSupport::Callbacks::CallbackChain:0x000000094002a0>
I figured out what to change by comparing the objects in Rails 4.1.16 vs 4.0.13.
Loading development environment (Rails 4.0.13)
UserInfoRequestSentAlert._validate_callbacks
Loading development environment (Rails 4.1.16)
UserInfoRequestSentAlert._validate_callbacks
* The Rails 4.0 version returns an Array, hence the broken `[0]` call.
* Call `#first` instead to get the first callback from `@chain`.
* Have a look what methods that has:
```
UserInfoRequestSentAlert._validate_callbacks.first.methods - Object.methods
```
* Try `#filter` to get the …
> Update hack to add extra alert type

- lib/views/help/privacy.cy.html.erb
- lib/views/help/privacy.html.erb
A user commented that the link is dead. The repo is private, so
will appear broken to anyone other than mySociety staff.
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/401
> [#401] Remove foi-regitser link

- lib/views/help/_contact_form.html.erb
- lib/views/help/contact.html.erb
With the new section, the page will look like:
And with the section open:
A bit of a non-ideal solution as now we have 2 copies of the form on the page but I can't think of how to fix that :(
Fixes mysociety/alaveteli#3708
> [#3708] Add a new contact us section for asking for help writing a request

- lib/config/wdtk-routes.rb
This mirrors the behaviour of `GET /local/london`.
Eventually we'll want to make `/london` a landing page in its own right,
but this just makes the URL accessible in case we want to get it out in
to marketing material.
See https://github.com/mysociety/whatdotheyknow-theme/issues/416.
> [#416] Add redirect for /london authorities

- lib/views/help/api.html.erb
A user commented that the link is dead. The repo is private, so
will appear broken to anyone other than mySociety staff.
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/414.
> [#414] Remove foi-regitser link

- lib/views/general/_popup_banner.html.erb
For https://github.com/mysociety/alaveteli-project/issues/19.
Anything else we should say?
> Add popup informing users of upcoming maintenance

- lib/views/general/_responsive_footer.html.erb
This hard coded URL is no longer correct. It should use www otherwise we
get a certificate error.
It _should_ redirect cleanly, but in any case, we should use the config
value here.
Fixes #433
> [#433] Use the donation_url config in footer

- lib/views/help/requesting.html.erb
Takes people to /pro
The `help#requesting` page is currently erroring
> Update the link to the pro signup page

- app/assets/stylesheets/responsive/custom.scss
Seems like a sensible default given they're clickable.
Initially required to make them look nice when displaying public body
notes in the batch builder.
**Without this change:**
**With this change:**
See https://github.com/mysociety/alaveteli-professional/issues/356.
Counterpart to https://github.com/mysociety/alaveteli/pull/4518 – can be merged independently though.
> [pro#356] Style details summaries like links

- lib/model_patches.rb
The UK Home Office use this address as a no-reply address, but because
it doesn't match our no-reply regexp we end up sending mail to it,
getting bounces and then causing admin burden.
This configures the `IncomingMessage#_calculate_valid_to_reply_to` check
to explicitly ignore this address.
Fixes https://github.com/mysociety/alaveteli/issues/1278
Counterpart to https://github.com/mysociety/alaveteli/pull/4722
> [core#1278] Ignore unusual no reply address

- lib/views/public_body/_more_info.html.erb
Both sites have updated their URL structure so our current links to
registration pages of charities no longer work. This commit adopts the
current URL structures, although this may be fragile in the case of the
Charity Commission as they are currently linking to a beta subdomain
with a banner indicating that it is a prototype.
Closes #486
> [#486] Update links to the Charity Commission and Charity Register sites

- app/assets/stylesheets/responsive/custom.scss
A small change that is needed as a result of https://github.com/mysociety/alaveteli/pull/4812
Without this WDTK's colour changes override core's focus styles
> ensure WDTK gets focus styles for keyboard users

- app/assets/stylesheets/responsive/custom.scss
Otherwise the pro livery unintentionally makes the link text invisible against the background
Before:
After:
Closes #496
> Ensure the skip to content link text is displayed in white

- lib/views/help/privacy.html.erb
Indicate that we won't by default remove decision-makers' names
from requests either.
> Make wording a bit more clear

- lib/views/help/unhappy.html.erb
* Now "referring" to the ICO
* Kept the `#complaining` anchor for backwards compatibility
* Text supplied in #455
Fixes #455.
> [#455] Update referring to ICO guidance

- lib/model_patches.rb
Authorities are dropping the `.gsi` subdomain, but the behaviour of this
address is still the same so we should continue to treat it as an invalid
reply address.
See https://github.com/mysociety/whatdotheyknow-theme/pull/478 for
historical context.
> Add updated Home Office no-reply email

- lib/views/alaveteli_pro/info_request_batches/_embargo_form.html.erb
Don't call InfoRequestBatch#all_requests_created?
This iterates through each `InfoRequest` associated with the
`InfoRequestBatch` and then `map`s each `PublicBody`, which is really
slow for big batches.
The real fix is to check `InfoRequestBatch#sent_at`…
--- a/app/models/info_request_batch.rb
+++ b/app/models/info_request_batch.rb
@@ -241,7 +241,7 @@ class InfoRequestBatch < ActiveRecord::Base
#
def all_requests_created?
-    requestable_public_bodies.empty?
+    sent_at.present?
end
…but there's some due diligence to do before we apply that.
Hack until we resolve mysociety/alaveteli#4891
> [Core#4891] Quick fix

- lib/controller_patches.rb
- spec/integration/spam_terms_integration_spec.rb
Hack for WDTK-specific cases.
If an anonymous user tries to submit spam terms in a request, just
redirect to the home page.
If a signed in user tries to submit spam terms in a request, ban them,
sign them out and then inform them they’ve been banned by sending them
to their profile page where they’ll be shown the ban message.
We can generate tmp/spam_terms.txt manually for now.
> Prevent spam terms being used in requests

- lib/views/help/privacy.html.erb
> the anchor name has changed at some point in the past year from
> `#public_request` to `#public_names`
Other themes are expecting to use `public_request`, so this should be
treated as a WDTK-theme specific problem, hence the compatibility fix,
rather than changing the anchor references in Alaveteli core.
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/523
> [#523] Add anchor for backwards compatibility

- lib/controller_patches.rb
- lib/views/help/_contact_form.html.erb
Requires https://github.com/mysociety/alaveteli/pull/4909
Required by mysociety/alaveteli#4865 
Connects to mysociety/alaveteli#4865 
Conditionally shows a reCAPTCHA on the contact form if the request appears to come from outside the UK
WDTK has started getting a high level of spam through the contact form so we wanted to add reCAPTCHA as a deterrent but without forcing it on to every Alaveteli instance.
> [#4865] Add reCAPTCHA to the contact form

- lib/views/general/_nav_items.html.erb
- lib/views/general/_responsive_footer.html.erb
Adds a "Volunteer" link to the navbar
...and a "Become a volunteer" link to the footer...
The existing "Run by Volunteers" link currently goes to `help/credits#helpus` which is a short section in the credits which links to `/help/volunteers`
Connects to #7
> [#7] More prominent volunteer links

- lib/views/request/_sidebar.html.erb
Updates whatdotheyknow-theme’s overridden `_sidebar` template to include the `_batch` partial that’s currently being added in core: https://github.com/mysociety/alaveteli/pull/4914
> Show parent batch, from request sidebar

- lib/views/admin_request/_hidden_user_explanation_reasons.html.erb
- lib/views/admin_request/hidden_user_explanation/_subject_access_request.text.erb
Closes mysociety/alaveteli#3543
Adapts the suggested text from mysociety/alaveteli#881 relating SAR requests (leaves the "Personal information"/"Personal correspondence" option as-is).
<a name="email_text"></a>
(artificially line wrapped to be readable on this page)
```
Subject: Your request on Alaveteli hidden
Dear Annie All Roles,
Your request 'Batch test' at http://10.10.10.30:3000/request/batch_test has been 
reviewed by moderators.
We consider it is not a valid FOI request as it was correspondence about your personal circumstances, and we have therefore hidden it from other users.
If you would like to know what information a public authority holds about you, you should make a “Subject Access Request” in private. The Information Commissioner’s website provides advice on accessing your …
```
> [#3543] Hide requests which appear to be SARs

- app/assets/stylesheets/responsive/custom.scss
Reporting correspondence or a comment isn't a primary action, so don't
make it look like one.
**Before:**
**After:**
> Use button-tertiary for report buttons

- lib/views/general/_default_footer.text.erb
- spec/mailers/request_mailer_spec.rb
Connects to #519
Requires mysociety/alaveteli#4936
Overrides the blank template in core to append a footer with a link to the Volunteer page
Example output:
```
To: Bob Smith <bob@localhost>
Subject: Someone has updated the status of your request
To help us keep the site tidy, someone else has updated the status of the
Freedom of Information request The cost of boring that you made to Ministry of Silly Walks, to "handled by post." If you disagree with their categorisation, please update the status again yourself to what you believe to be more accurate.
Follow this link to see the request:
http://alaveteli.10.10.10.30.xip.io/request/the_cost_of_boring_two
-- the Alaveteli team
----------------------------------------------------------
Help WDTK - …
```
> Add request_mailer footer with volunteer link

- app/assets/javascripts/tests.js
- app/assets/stylesheets/responsive/custom.scss
- lib/alavetelitheme.rb
- lib/helpers/donation_helper.rb
- lib/views/request/_sidebar.html.erb
- lib/views/request/show.html.erb
- spec/donation_helper_spec.rb
Moves the red donation banner from the sidebar to the end of the page, using JavaScript, if the current user is in Context Experiment group 1.
Also tracks clicks on the donation banner button, no matter where it’s located, so we can use that as the goal in our Content Experiment.
I’ve [set up the experiment](https://analytics.google.com/analytics/web/#/report/siteopt-experiments/a24614779w48006686p48388638/) but not started it yet. Guess we could start it now, it wouldn’t have any effect, but I figured we should get this PR merged and deployed first, just for tidiness ;-)
See mysociety/whatdotheyknow-theme#542 and (more specifically) mysociety/alaveteli-experiments#115.
> A/B test position of donate-cta on request page

- lib/controller_patches.rb
Requires mysociety/alaveteli#4939
Connects to mysociety/alaveteli#4939
Overrides the reCAPTCHA controller code in core to restrict it to request from outside the UK
> [#4939] Only show user-to-user contact captcha if request is from outside the UK

- lib/views/followups/_followup.html.erb
Override the slightly simpler template, including the fix for showing part of the response form when new responses are not being accepted for the current request.
Connects to mysociety/alaveteli#4985
Requires mysociety/alaveteli#5033
> [#4985] Only show the followup form if the request is open to new responses

- lib/views/request/_sidebar.html.erb
Fixes mysociety/alaveteli#5161
Expands the `utm_source` param from "`whatdotheyknow`" to "`whatdotheyknow.com`" for the outbound links to the donations page in the sidebar.
The donations page shows WDTK-specific content and (I think) flags the donation as a contribution towards running WDTK, but only if we pass in the correct string. Also it's fractured the metrics a little bit as the footer link already does this "correctly" so ... that's a pain.
(Our own inbound links should continue to be `whatdotheyknow`/`site_name.downcase` (the resulting text is identical) and as this is a WDTK-specific change, there's no benefit - probably the opposite, in fact - to altering this in core.)
(ok, mostly for my benefit as I can never keep these in my head properly)
`utm_source` is a required param for …
> [#5161] Fix utm_source

- lib/views/help/credits.html.erb
- lib/views/help/requesting.cy.html.erb
- lib/views/help/requesting.html.erb
Needed to use the new dynamic routing workaround for the Rails 5 changes
Fixes the `No route matches {:action=>"unhappy", :controller=>"help"} missing required keys: [:template]` style errors that affect `help/requesting` and `help/credits`
> Use template instead of action with help_general_path

- lib/model_patches.rb
- spec/model_patches_spec.rb
Closes #564
* Adds a `User#can_send_survey?` method to test whether the user is eligible to receive a survey alert
* Adds `!user.active?` as a reason to not send the survey alert
* Delegates the user-based part of `RequestMailer.alert_survey`'s decision whether to send a survey alert to the new `User#can_send_survey?` method
* Uses `#deliver_now` instead of the deprecated `#deliver` method when sending survey alerts
We want to stop sending survey alerts to suspended users (by checking the `User#active?` method)
> [#564] Don't survey suspended users

- lib/views/help/_sidebar.cy.html.erb
- lib/views/help/_sidebar.html.erb
- lib/views/help/pro.html.erb
Requires https://github.com/mysociety/alaveteli/pull/5292
Connects to https://github.com/mysociety/transparency-adessium/issues/18
Only linked to if pro is enabled. The routing in core also has a
constraint.
> Add pro help page

- app/assets/javascripts/tests.js
- app/assets/stylesheets/responsive/_print_style.scss
- app/assets/stylesheets/responsive/custom.scss
- lib/views/request/_sidebar.html.erb
- lib/views/request/show.html.erb
* Move the request page donation banner out of the sidebar, to its new home at the bottom of the correspondence list (replacing the AskTheEU banner that was there previously).
* Set up Google Optimize on the request pages, and have it pick one of three wording variations for the donation button.
* Trigger a Google Analytics event when the donation button is clicked.
Meanwhile, a [Google Optimize](https://optimize.google.com/optimize/home) experiment has been set up (as per https://github.com/mysociety/research/issues/194) with three variants (0, 1, and 2) and looking out for an "objective" of a Google Analytics event with a `category` of `Request page donate button`.
We’ll need to remember to "Start" the Optimize experiment, once we go ahead with all this.
Part of …
> Second phase of request page donation button A/B testing

- app/assets/stylesheets/responsive/custom.scss
- lib/views/request/_sidebar.html.erb
Reconciles the request page sidebar with core and improves styling
> Reconcile with core & sidebar style

- lib/alavetelitheme.rb
Required by mysociety/alaveteli#3970
Uses `before_action` instead of `before_filter`
`before_filter` was deprecated in Rails 4.2 and will be removed altogether in 5.1
https://edgeguides.rubyonrails.org/4_2_release_notes.html#action-pack-notable-changes
https://github.com/rails/rails/blob/5-1-stable/actionpack/CHANGELOG.md#rails-510-april-27-2017
> Define filters with before_action instead of before_filter

- app/assets/javascripts/tests.js
- lib/views/request/show.html.erb
Fix for two mistakes in 636b881 (original PR #591):
1. Makes sure that `dataLayer` is defined at pageload.
2. Avoids calling `ga('send', 'pageview')` twice.
Also, the `content_for :ga_pageview` block is now defined *before* the `render partial => 'ga_events'` block so our `ga` `create/require/send` calls are in the [same order that the docs recommend](https://support.google.com/optimize/answer/6262084). I don‘t think it makes a difference whether the pageview is sent before or after the Optimize ID is included, but at least this way it matches the docs.
@garethrees Once you merge and deploy this, I _think_ the Optimize experiment should work.
Related:
* https://github.com/mysociety/whatdotheyknow-theme/pull/591
* https://github.com/mysociety/research/issues/194
> Fix Google Optimize loading on request pages

- lib/views/help/privacy.html.erb
Fixes #563.
The current text currently addresses registered users. WhatDoTheyKnow
processes the personal data of others including those identified in FOI
responses so it would be useful if the text was more generic.
Also includes minor formatting fixes.
Before:
After:
> [#563] Update /help/privacy#legal_basis

- app/assets/javascripts/tests.js
Fixup for 636b881b6e66a4d0177a48f4a819f4ac8275bd5d. The missing `e` parameter meant that our callback function didn’t intercept the browser’s default page navigation, and the Analytics event wasn’t recorded before the browser left the page.
> Pass event parameter to donate button click handler

- app/assets/stylesheets/responsive/_mixins.scss
Add disabled button style used on the new Stripe forms when there are errors preventing it from being submitted.
I'm pretty sure the mixin additions are fine but unsure about the impact of removing the `color: inherit`
If left in place the hover style looks like:
> Disabled button style

- lib/views/public_body/_more_info.html.erb
Replaces #582 
> This PR expands on #491 to include links to Companies House and the ICO's data protection register. It's conceivable that for some bodies we may only use the DPR, however, for others, we may end up using both.
> 
> Some examples to test with:
> - [DfT OLR Holdings Limited](https://www.whatdotheyknow.com/body/dohl); has 'ch' tag
> - [Glasgow City Council](https://www.whatdotheyknow.com/body/gcc); has 'dpr' tag
> - [Network Rail Limited](https://www.whatdotheyknow.com/body/network_rail); has 'ch' and 'dpr' tags
> 
> This is the first time I've wrangled with the Alaveteli codebase, so, _please be gentle_ 😊
> 
> Closes #581
> [#581] Add links to company house and ico

- lib/model_patches.rb
Adds `autoresponder@sevenoaks.gov.uk` as an invalid reply 
address meaning users will not be able to send follow-ups or internal 
review requests to it.
This caused confusion for a user who contacted us because they had received a delivery failure message after replying to the above.
Linked to #670
> Add Sevenoaks responder as invalid reply address

- lib/views/help/about.html.erb
- lib/views/help/privacy.html.erb
- lib/views/help/requesting.html.erb
Whilst browsing the help pages I saw a couple of tweaks that could be made.
- A grammatical correction to the about page
- Add some bold text to the requesting page
- Change 'post' to 'postal mail' on the privacy page
Plus, it gave me a good opportunity to play with the basics of GitHub etc! Hope I've done it right, apologies in advance if not 😃
> Minor edits to the WhatDoTheyKnow help pages

- lib/model_patches.rb
- lib/scotland_late_calculator.rb
- spec/model_patches_spec.rb
Scotland has extended deadlines during COVID-19. This applies a custom
LateCalculator to authorities tagged `scotland` to reflect the new
timelines.
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/672.
**New late calculation** for authority tagged `scotland`:
Remove the late calc – still get the same due date for requests made during covid-19.
Not sure what situations this might get recalculated in, but I imagine we'll be _mostly_ correct. Given its a temporary measure, I think we can live with a few deviations.
> Add ScotlandLateCalculator

- lib/views/help/unhappy.html.erb
Add some statistics from mySociety research on the success of internal 
reviews to encourage requesters to use them when necessary. Fixes #631
Before:
After:
> Add stats on success of internal reviews to 'unhappy' help page

- lib/views/help/unhappy.html.erb
Make it clear that an internal review and a referral to the ICO or
separate steps.
> Separate next steps

- lib/model_patches.rb
Adds `H&FInTouch@lbhf.gov.uk` to the list of invalid reply addresses. This should prevent replies etc being sent to it which bounce (see mysociety/alaveteli#3465)
We've had a few of these for this email address, hopefully this will be a workaround to prevent problems for users.
> Add H&F In Touch email as an invalid reply address

- lib/views/followups/_followup.html.erb
- lib/views/help/how.html.erb
- lib/views/help/officers.html.erb
- lib/views/help/privacy.html.erb
- lib/views/help/unhappy.html.erb
A number of outbound links across the WhatDoTheyKnow help pages have become broken. This PR replaces all broken links identified this evening with suitable replacements. In one instance (FOI Register) I've removed the link as I cannot find a suitable replacement.
Fixes #628 
Fixes #635
> Fix broken outbound links

- lib/views/public_body/_more_info.html.erb
This PR adds three new tags ('urn', 'spuid', and 'matuid') to _more_info.html.erb, which allow referencing of the DfE's  "Get Information about Schools" website.
These additions should add a new entry to the respective public body pages under "More about this authority" where the tag 'urn', 'spuid', or 'matuid' appears in the body tags;
Example bodies:
[Canterbury College](https://www.whatdotheyknow.com/body/canterbury_college)
**Tags**: `dpr:Z7597166 fei urn:130730`
The 'dpr' tag should resolve to: https://ico.org.uk/ESDWebPages/Entry/Z7597166
The 'urn' tag should resolve to: http://get-information-schools.service.gov.uk/Establishments/Establishment/Details/130730
[Holyport College](https://www.whatdotheyknow.com/body/holyport_college)
**Tags**: `ch:07930340 dpr:ZA046885 free_school …
> [#698] Add new tags to _more_info.html.erb to allow users to search DfE

- lib/views/help/privacy.html.erb
Removed reference to upcoming policy, added link to policy.
Policy: https://docs.google.com/document/d/1ytnM2U3fjMgri49YizFDt_9A-2uQmcF4qnGgFDMJpk0/edit#
Addresses #685
> Added reference to data sharing policy

- lib/model_patches.rb
N/A - Issue not raised. Support mailbox correspondence.
Adds a couple more addresses added to ReplyToAddressValidator.invalid_reply_addresses
This will hopefully help our users by preventing them replying to emails that do not accept replies.
N/A
N/A
N/A
> Add 2 new invalid reply addresses

- lib/views/general/_responsive_footer.html.erb
Linking to "Want to help?" section was confusing, it is much clearer to link to the "Volunteers" section, and credits them properly.
I think it used to say "Run by volunteers... and you!" and the "and you!" linked to "Want to help?". I'm guessing it got stuck with that value while being updated.
> Fix footer link "Run by volunteers"

- lib/model_patches.rb
N/A - Issue not raised. Support mailbox correspondence.
Adds invalid addresses for Dundee City Council, Student Loans Company, and the Department of Health and Social Care to ReplyToAddressValidator.invalid_reply_addresses
This will hopefully help our users by preventing them replying to emails that do not accept replies.
N/A
N/A
N/A
> Add new invalid addresses to model_patches.rb

- lib/model_patches.rb
N/A
This patch adds two new no-reply addresses to model_patches.rb.
Two directorates at the Home Office are issuing responses (such as [691163](https://www.whatdotheyknow.com/request/reporting_of_reportable_poisons#incoming-1651063), and [689448](https://www.whatdotheyknow.com/request/home_office_financial_contributi#incoming-1642692)) from mailboxes that do not accept responses.
This patch complements our existing solution for problematic mailboxes at the Home Office and improves user experience by ensuring we aren't routing responses into an apparent ether.
As per previous patches, this is a direct addition to existing code - there are no specific implementation notes.
N/A
N/A - happy days 😊
> Add two new Home Office addresses to model_patches.rb

- lib/model_patches.rb
mysociety/alaveteli#3465
This patch adds an email address for Oxfordshire County Council (as seen in request 684973 and 690752) to the invalid list.
This is needed as a workaround for the issue described above which is affecting some WDTK users who attempt to reply to a specific mailbox that Oxfordshire County Council is issuing responses from.
N/A, this is a straightforward addition to existing code.
N/A
This does the same as #720, sadly it arose just after the previous patch was committed. 🙃
It's worth noting that the email address quoted here has a capital letter in the domain name - this is consistent with how it is presented by the OCC email system in replies from their staff (e.g. in message [1653110](https://www.whatdotheyknow.com/admin/incoming_messages/1653110/edit)).
> [#3465] Add one new address to invalid list model_patches.rb

- lib/model_patches.rb
We were relying on Rails to not change the order of validation callbacks
but in Rails 6 this has now changed. Now we find the relevant callback
using class and attribute before updating its options.
> Improve adding custom inclusion validation options

- lib/model_patches.rb
Fixes #724 
This patch adds a no-reply address for Bedfordshire Police to model_patches.rb
Emails issued by the public body's eCase system are being sent from an email address that doesn't accept replies. This workaround allows Alaveteli to automatically recognise the address and send any responses to the main address for the public body.
N/A
N/A
Nothing specific, this is long standing code 😊
> Add one address (Bedfordshire Police) to model_patches.rb

- lib/model_patches.rb
Fixes #730 
This patch adds new no-reply addresses for both Aberdeen City and Dundee City Council to model_patches.rb
Correspondence being issued from public bodies from 'no-reply' email addresses which our users were unable to respond to.
N/A
N/A
Another minor change to our long-standing code, there are no specific notes. 🎉
> Add Dundee and Aberdeen City to model_patchees.rb

- lib/model_patches.rb
Fixes #733 
This patch adds a new no-reply addresses for Worcester City Council to model_patches.rb
Correspondence being issued from public bodies from 'no-reply' email addresses which our users were unable to respond to.
N/A
N/A
This can be merged at the same time as #731 - I've kept it as a separate PR given the time that has passed between the two.
> Add address for WCC to model_patches.rb

- lib/model_patches.rb
N/A - No issue raised for this one.
This patch adds a new no-reply addresses for Castle Point Borough Council to model_patches.rb
Correspondence being issued from public bodies from 'no-reply' email addresses which our users were unable to respond to. This particular address was located on the thread at https://www.whatdotheyknow.com/request/fraud_investigation_61 to Castle Point Borough Council.
N/A
N/A
N/A
> Add Castle Point BC invalid reply address

- lib/views/help/house_rules.html.erb
Fixes #735 
This PR expands on the bullet point surrounding others' personal information on the WhatDoTheyKnow.com House Rules.
Currently the House Rules state:
- Do not post other people’s sensitive personal data to the site.
- Do not use WhatDoTheyKnow to request your personal information from authorities. [...]
Neither of these closely correspond to the situation where a requester makes an inappropriate request asking for another person's personal information, which will almost certainly be rejected.
The situation isn't clear cut as sometimes it is fair and reasonable to request, and receive, others' personal data eg. expenses/allowances for senior public officials.
N/A
N/A
> [#735] Expand House Rule on others' personal information

- lib/views/public_body/_more_info.html.erb
Fixes #711 
This patch updates the URLs that we use for Charity Commission and Companies House databases in the _more_info.html.erb sidebar.
The URL format for Companies House is a straight find-and-replace of the domain name, replacing `beta.companieshouse.gov.uk` with `find-and-update.company-information.service.gov.uk`.
The URL for the Charities Commission is a more significant change - replacing the domain name and parameters.
Both databases have moved from beta to production, and as such, the domain name and URL format have changed. This is more problematic for the Charity Commission as links from the old production and beta systems do not degrade gracefully.
This is an update to existing code - there are no specific tests that need to be conducted; however, to ensure that the …
> Update links to charity/company databases in _more_info.html.erb

- lib/config/wdtk-routes.rb
#747 
This patch adds a redirect for /england to wdtk-routes.rb
To ensure feature parity between other national pages for WDTK users in the UK - we hadn't added an explicit entry for /england in previous work that had been implemented. We tag over 700 bodies with the specific tag of "england", therefore this functionality might be helpful for our users.
There is no specific implementation notes.
N/A
This code is based on #417 and recent updates.
> Add redirect to wdtk-routes.rb for England

- lib/views/help/_sidebar.html.erb
- lib/views/help/about.cy.html.erb
- lib/views/help/contact.cy.html.erb
- lib/views/help/credits.html.erb
- lib/views/help/house_rules.html.erb
- lib/views/help/officers.cy.html.erb
- lib/views/help/officers.html.erb
- lib/views/help/privacy.cy.html.erb
- lib/views/help/privacy.html.erb
- lib/views/help/requesting.cy.html.erb
Fixes #751 
This PR swaps out the apostrophe character that we've used in some help pages.
We've inconsistently used both `'` and `’` within help documents, which creates a slight semantic issue and makes the code slightly clunky to work with.
This is a straight swap of characters _in almost all_ cases - taking care not to mess with legitimate instances of the `'` character within links.
N/A
I have intentionally skipped unhappy.html.erb since changes to this file will likely be committed elsewhere.
_This replaces a previous PR which contained a glitch that had been pushed in error._
> [#751] Fix apostrophe tags in help pages

- lib/views/help/how.html.erb
None logged.
Fixes some minor typos in how.html.erb and removes an undefined acronym.
To correct some typos, and remove a potentially unclear acronym for ease of clarity.
A very minor update to existing code - there is no functional changes so this is a straight merge.
N/A
N/A - happy days 🥳
> Fix minor typos in how.html.erb

- lib/model_patches.rb
Requires https://github.com/mysociety/alaveteli/pull/6015.
Adds refusals/exemptions from the Freedom of Information Act 2000 [1].
Fixes https://github.com/mysociety/alaveteli/issues/6002.
[1] https://foiwiki.com/foiwiki/index.php/Freedom_of_Information_Act_2000
> Configure refusal references

- lib/model_patches.rb
Fixes #759 
This patch adds a  new no-reply system mailbox used by the ONS to model_patches.rb
Notification emails being sent from the ONS are being sent from an invalid address, therefore when users reply they receive a bounceback, which generates support emaill
Nothing explicit - this is a minor update to well established code.
N/A
N/A - happy days 😃
> [#759] Add email address for ONS to model_patches.rb

- lib/model_patches.rb
Adds a new email address to the Reply To Address validator in model patches to prevent replies being sent to this address.
Any email sent by Alaveteli to this email address will fail due to https://github.com/mysociety/alaveteli/issues/3465
> Add NMC invalid email address

- lib/model_patches.rb
This PR adds an email address for Lambeth Borough Council to the list of invalid reply addresses.
It seems that LBC are automatically bouncing replies sent to this email address unless they contain the unique reference number.
Per support mail received by WDTK support.
> Add Lambeth BC invalid email address

- app/assets/stylesheets/responsive/custom.scss
- lib/controller_patches.rb
- lib/help_page_history.rb
- lib/views/help/_history.html.erb
- lib/views/help/about.html.erb
- lib/views/help/alaveteli.html.erb
- lib/views/help/api.html.erb
- lib/views/help/beginners.html.erb
- lib/views/help/complaints.html.erb
- lib/views/help/credits.html.erb
- lib/views/help/house_rules.html.erb
- lib/views/help/how.html.erb
- lib/views/help/officers.html.erb
- lib/views/help/principles.html.erb
- lib/views/help/privacy.html.erb
- lib/views/help/pro.html.erb
- lib/views/help/requesting.html.erb
- lib/views/help/unhappy.html.erb
- lib/views/help/volunteers.html.erb
- spec/help_page_history_spec.rb
Adds a generic "changes" section to the bottom of most help pages.
Avoids having to write this individually each time we think we need it (#700, #754) and keeps things like the page anchors consistent.
> Help page version history

- lib/model_patches.rb
Fixes #793 
This patch adds a new no-reply addresses for Coventry City Council to model_patches.rb
Correspondence being issued from public bodies from 'no-reply' email addresses which our users were unable to respond to; therefore, to prevent our users being _"sent to coventry"_, this patch will actually allow their messages to be sent to Coventry City Council instead! 😀
N/A
N/A
Nothing of note - happy days.
I'll get me coat for the terrible pun though!
> [#793] Add address for Coventry City Council to model_patches.rb

- lib/model_patches.rb
Fixes #796; Fixes #802 
This patch adds two new addresses to model_patches.rb, for bodies Highways England and 3C Shared Services. The latter relates to three Councils (Cambridge City, Huntingdonshire District, and South Cambridgeshire District Councils)
Correspondence being issued from the 3C Shared Services bodies is being sent from 'no-reply' email addresses which our users were unable to respond to.
In addition, the Highways England address has an ampersand, which currently causes a system error. The root cause of this is being investigated upstream [mysociety/alaveteli#3465 (comment)](https://github.com/mysociety/alaveteli/issues/3465#issuecomment-810978437), but putting a workaround in place while we wait on a fix is a good thing to do from a user-experience perspective.
Nothing of …
> [#796, #802] Add addresses for Highways England and 3C Shared Services to model_patches.rb

- lib/views/general/_frontpage_how_it_works.html.erb
> FOI and similar access to information laws apply to public bodies, not
> publicly-funded bodies.
Minor part of https://github.com/mysociety/whatdotheyknow-theme/issues/791
> [#791] Fix wording of citizen rights

- config/refusal_advice/exemptions.yml.erb
Add short title to each exemption for better user understanding.
I used a hyphen rather than a colon because after processing the ERB the
YAML interpreter was expecting the whole string to be quoted. This means
we'd have to do something like `<%= _(%q("Section 12: Foo")) %>` which
is pretty gross.
Ideally these labels would support HTML rendering so that we could bold
the section number, but this is the easiest fix for now.
Fixes https://github.com/mysociety/alaveteli/issues/6237
> [alaveteli#6237] Add exemption titles to wizard labels

- lib/views/help/unhappy.html.erb
We had a user support query around whether British citizens can make FOI
requests to the EU.
* Many WDTK users may be EU citizens and British residents.
* The withdrawal agreement has a section on this [1] (p182 of the document,
p187 of the PDF). it looks as if UK people and entities still have a
right of access to EU documents: "in connection with activities of the
Union pursuant to this Agreement".
* AskTheEU's help page suggests that most people can ask anyway [2]
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/819
[1] https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/840655/Agreement_on_the_withdrawal_of_the_United_Kingdom_of_Great_Britain_and_Northern_Ireland_from_the_European_Union_and_the_European_Atomic_Energy_Community.p …
> [#819] Tweak advice we give for asking EU authorities

- lib/views/help/how.html.erb
- lib/views/help/officers.html.erb
This PR has two commits to change the use of the word "taxpayers'" to "public".
As per the suggestion at #838 and the reasons given. Also recently came up on a review@ thread.
Fixes #838.
> [#838] Change references in help pages

- config/refusal_advice/exemptions.yml.erb
mySociety house style is to capitalise the first letter of a title but
not for subsequent words. The legislation [1] uses this style too.
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/856.
[1] https://www.legislation.gov.uk/ukpga/2000/36/section/11
> [#856] Consistent capitalisation of refusals

- lib/model_patches.rb
Fixes #860 
This patch adds the email address for the Ministry of Justice Digital and Technology team to model_patches.rb 
Workaround for known bug which causes issues with email addresses where special characters are present.
Nothing specific, this is the usual 'tried and tested' change to mitigate the issue described in https://github.com/mysociety/alaveteli/issues/3465
N/A
N/A
> Add email for MoJ Digital and Technology to model_patches.rb

- lib/model_patches.rb
Fixes #881 
This patch adds the Citrix ShareFile notification email address to model_patches.rb.
This is needed to prevent users from sending messages to a no-reply address (which is unroutable) and falling into a loop.
Nothing specific, a minor change to long-standing code.
N/A
N/A
> [#881] Add citrix sharefile notification address to model_patches.rb

- lib/model_patches.rb
- spec/model_patches_spec.rb
For some reason we keep seeing email alerts getting disabled for the
Internal Admin User on WhatDoTheyKnow.
We think this is somehow related to the Unsubscribe link rendered via
`app/views/track_mailer/event_digest`. Perhaps someone is mistakenly
clicking it, or an email client is pre-emptively clicking it to cache
content? Who knows!?
This commit checks that the user is _not_ the Internal Admin before
disabling. I used a new module with `prepend` so that we can call
`super` to rely on core behaviour, rather than having to keep the main
method definition in sync.
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/931.
To test:
```ruby
admin_token = User::EmailAlerts.token(User.internal_admin_user)
app.users_disable_email_alerts_url(token: admin_token)
user_token = …
```
> [#931] Prevent disabling of Internal Admin email alerts

- lib/model_patches.rb
#939 
This change adds the no-reply address used by Somerset West & Taunton Deane council to model_patches.rb
The council issues their replies from a no-reply address, which can get our users stuck in a loop.
Nothing specific, it's the usual tried and tested code.
Of slight note perhaps - the address directly above has an apostrophe in it, I'm not certain whether or not this needs to be escaped. I assume not, given the code hasn't malfunctioned, but I'm not 100% certain!
N/A
N/A
> [#939] Add Somerset West and Taunton Deane to model_patches.rb

- lib/views/help/_contact_form.html.erb
- lib/views/help/contact.html.erb
Fixes #961 
This change replaces "volunteers" with "team", along with minor phrasing changes, on /help/contact and in the relevant partial for the contact form.
This is needed to better reflect the increased diversity of the team that handles user support correspondence, and the changing ways in which WhatDoTheyKnow / WhatDoTheyKnow Pro is administered. This is discussed in greater detail on the linked issue.
Nothing controversial, this is a series of minor changes to established code.
N/A
N/A
> [#961] Change wording on contact form

- lib/views/help/privacy.html.erb
We process all GDPR RTE requests under the legal basis of Legitimate Interests,
so using the word "consent" in this particular context is a little confusing given
it's a specific term for another legal basis for processing.
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/1035
> Fix phrasing of legal basis for processing

- lib/model_patches.rb
When information is sent via the file transfer service it comes from a no reply email address. This address then gets picked up as the reply address for WhatDoTheyKnow users creating a bounce message rather than going through to the authority
> Add no reply address for The Adjudicator's Office

- lib/model_patches.rb
When information is sent via the file transfer service it comes from a no reply email address. This address then gets picked up as the reply address for WhatDoTheyKnow users creating a bounce message rather than going through to the authority
> Add no reply address for Cambridgeshire County Council

- config/refusal_advice/section_12_actions.yml.erb
Fixes #1011 
This patch corrects a typo in the answer for S12-A10.
A WhatDoTheyKnow user kindly alerted us to a typo, meaning that we had the the guidance in S12-A10 as to backward aggregation mixed up. As per paragraphs 49 and 50 of the [ICO guidance](https://ico.org.uk/media/for-organisations/documents/1199/costs_of_compliance_exceeds_appropriate_limit.pdf), the relevant period is **20 days ‘forward'** and **60 days ‘backwards’**, with the total aggregation period not exceeding 60 working days.
Nothing to note, it's changing a '2' to a '6'
N/A
N/A
> [#1011] Fix typo in ICO guidance

- lib/public_body_questions.rb
**Queries to: https://www.whatdotheyknow.com/help/contact**
Fixes #1008 
This adds public body questions for bodies 525, 1294, and 12848.
To reduce a misuse vector, and improve the quality of our advice to site users.
Copy has been done relatively quickly, feel free to suggest  any amendments.
This will work best once https://github.com/mysociety/alaveteli/pull/6807 is deployed, but it's by no means compulsory - it's just a heading difference.
N/A
As discussed on review@ - this is a follow-up to the mockup version.
> Add LSE questions

- lib/model_patches.rb
Prevent deletion of variants. We don't currently use variants and this
causes timeouts (when doing a remote globs to find variant files to be
deleted) when using a ActiveStorage SFTP service.
See: https://github.com/rails/rails/blob/6-1-stable/activestorage/app/models/active_storage/blob.rb#L287-L290
> Add patch to ActiveStorage::Blob#delete

- lib/config/wdtk-routes.rb
- lib/views/outgoing_mailer/_followup_footer.text.erb
Fixes #1106
This adds the URL for the ICO anonymisation code to wdtk-routes.rb, and adds the corresponding URL to the outgoing mailer file _followup_footer.text.erb
The URL is useful to have, for ease of use, when responding to public bodies who have disclosed data improperly. It is also helpful to include in outgoing mail, as this gives some clear and helpful guidance to those who might be unfamiliar with the correct way of disclosing statistical data.
This complements the existing ICO guidance we link (I wish we had named it more specifically!)
N/A
Hopefully nothing contentious, although please verify that I've added the link in _followup_footer.text.erb (70d2311ed10291eaa91caeaa201de73537834168) correctly.
> [#1106] Add ICO anonymisation code to wdtk-routes.rb and update outgoing mailer

- lib/views/help/about.cy.html.erb
Still mentions UKCOD, in Welsh.
Thanks to @FOIMonkey for the translation.
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/1133.
> [#1133] Fix company names on /cy/help/about

- lib/model_patches.rb
Fixes #1262 , fixes #1263, fixes #1265
This adds two addresses to the list of 'no-reply' addresses in model_patches.rb
We need to update this list to include Dudley MBC, as their FOI system generates responses from an invalid address. We also need to add the generic address used by OneDrive / Sharepoint Online, as this is now used by a number of bodies to send messages containing large files.
Nothing special - adds to the well established list contained within the file.
N/A
N/A
> [#1262, #1263, #1265] Add Dudley MBC and Sharepoint no-reply email addresses to model_patches.rb

- lib/model_patches.rb
- spec/model_patches_spec.rb
This has been removed upstream from Alaveteli.
See: https://github.com/mysociety/alaveteli/pull/7142
> Remove calls to InfoRequest#is_batch_request_template?

- lib/views/help/contact.html.erb
Fixes #1270 
This patch resumes the rendering of the WDTK team contact form, which had not been rendering correctly owing to a bug.
The fix in #1208 had renumbered the form to houdini goal 4, but this had not been factored into one of the labels - therefore the contact form would only render if the "I need help writing a freedom of information request." option was chosen.
I have noted that we render a different piece of help text on the "I need help writing a freedom of information request" and "I have another issue, or feedback relating to the WhatDoTheyKnow.com website, that I want to raise with the team that runs WhatDoTheyKnow" forms, therefore, rather than have them as the same goal, I've set the default contact form as houdini goal **5**.
I've also renumbered the preceding, so that …
> [#1270] Resume rendering of the contact form

- lib/views/help/requesting.html.erb
Fixes #1311 
The mySociety style guide identified the old wording as being a phrase that shouldn't be used due to the racial connotations. This fixes the issue using the suggested alternative.
> Fixes mySoc styleguide conflict

- lib/model_patches.rb
Fixes  #1273
Fixes  #1274
Adds no-reply email addresses for Tewekesbury BC and Publica Group to model_patches.rb
Public bodies responding from no-reply email addresses, which causes frustration for users.
Nothing special to note.
N/A
N/A
> Add no reply emails for Tewkesbury BC and Publica Group

- lib/views/help/how.html.erb
Fixes #1190.
Updates introduction section of 'How we run WhatDoTheyKnow' help page to better reflect increased staff involvement and bring in line with support email footer.
Screenshot of new help text:
> Update intro section of how help page

- lib/views/help/unhappy.html.erb
Fixes #1068.
Updates the statistics on success of internal reviews with new statistics from mySociety Research Team.
> [#1068] Update statistics in Internal Advice help

- config/refusal_advice/section_14_actions.yml.erb
- config/refusal_advice/section_43.yml.erb
- config/refusal_advice/section_43_actions.yml.erb
Fixes #1328 
This fixes links to the Information Commissioner's guidance in the refusal advice for s14 (Vexatious) and s43 (Commercial Interests).
The ICO are _slowly_ moving away from the PDF based guidance docs, and their website doesn't degrade the links gracefully, meaning we're dispensing out of date information.
I think I've clobbered all of the links in the s14 and s43 set. I've made a brief check of s12 and s35 and they still appear to be okay.
n/a
The format here is a carbon copy of how things were already setup. I did ponder if it would be practical to specify the URLs in one place and have a call back - but decided not to meddle with the existing format.
> [#1328] Update ICO links for s14 and s43 in refusal advice

- lib/views/public_body/_more_info.html.erb
Simple version of https://github.com/mysociety/whatdotheyknow-theme/issues/818.
Link to MapIt area if a body is tagged with `mapit:AREA_ID`, and/or the
"parent" area if tagged with `parent_mapit:AREA_ID`.
Also links to an on-site search to find other bodies in the same area.
Helps users figure out if a body is relevant to their interests.
Not sure about the "Parent area" phrasing – could we improve that?
> [#818] Add special link for MapIt areas

- lib/views/help/_contact_form.cy.html.erb
- lib/views/help/_history.cy.html.erb
- lib/views/help/about.cy.html.erb
- lib/views/help/about.html.erb
- lib/views/help/contact.cy.html.erb
- lib/views/help/house_rules.html.erb
- lib/views/help/how.html.erb
- lib/views/help/officers.cy.html.erb
- lib/views/help/privacy.cy.html.erb
- lib/views/help/requesting.cy.html.erb
- lib/views/help/unhappy.html.erb
Fixes #1326 
_#650_
This is a chunky PR, but in essence it:
- Removes the contact form from `lib/views/help/contact.cy.html.erb` and sets up a partial
- Adds partial `lib/views/help/_history.cy.html.erb`, so that we no longer present the English version on /cy
- Replaces reference to DPA 1998 and briefly covers RtE / RoA (SAR)
- Roughly translates aforementioned
- Fixes a couple of broken links
We had a couple of broken links. At the same time, our Welsh help pages are quite a bit out of sync, so this makes a first attempt at trying to rectify this.
Nothing of particular note; however, I would note that although `lib/views/help/contact.cy.html.erb` references the new Volunteer contact form, the partial hasn't been translated, as I believe it would need the specs to be updated. We could …
> [#1326] Update help pages

- lib/views/help/how.html.erb
Fixes #1180
This updates the content of section "Membership of the admin team" based on the agreed text.
Improvements being made as part of the implementation of the volunteer plan and have been ratified by the Service Manager and team.
`/lib/views/help/how.html.erb` has mixed use of ' and ’ (U+2019) - the latter being the predominant. As this is what's already there, I haven't sought to revise any existing content. We can do that at another point.
N/A
N/A
> [#1180] Update admin team section in `/help/how.html.erb`

- lib/views/help/how.html.erb
- lib/views/help/unhappy.html.erb
Information may be out of date on the day it is published
Information may be out of date on the day it is published. This is because FOI is  aright to information held by public authorities that may or may not be up to date.
Improves help text. Provides clarity to users.
See above.
See above.
N/A
See also: https://wdtkwiki.mysociety.org/wiki/Draft_legal_notice_for_the_site
> help text - info may be out of date

- lib/views/general/_before_head_end.html.erb
Makes the browser URL bar a nice colour [1]. Uses a pro/non-pro
appropriate colour by checking the user. Ideally we'd interpolate the
SCSS setting but don't think we have an easy way of doing that right
now.
In the case of the Pro theme, the darker colour looked better than the
lighter part of the gradient.
[1] https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color
**BEFORE**
**AFTER**
> Set theme-color meta tag

- lib/model_patches.rb
Fixes #1387
This patch adds two generic generic email addresses (used by Civica iCasework) to `model_patches.rb`
Per #1387, some authorities using iCasework are issuing automated reminders, prompting for a user's response. Unlike most iCasework messages, these are being sent from a `no-reply` email address.
As these are being added to the request thread, and as they take the same form as the 'original' message, it is likely a user will respond to them and get a frustrating outcome. This then becomes a nuisance to deal with, as we cannot easily re-direct correspondence so have to give advice as to how this can be done.
Nothing of note, this is long established code.
N/A
N/A
> [#1387] Add iCasework DNR email to `model_patches.rb`

- lib/views/help/privacy.html.erb
Updated link.
New link: https://ico.org.uk/media/for-organisations/documents/1164/recognising-a-request-made-under-the-foia.pdf
Old link: https://ico.org.uk/global/page-not-found?aspxerrorpath=/media/1043418/consideration-of-the-identity-or-motives-of-the-applicant.pdf
The old link no longer works.
See above.
Fixes help text.
See above.
N/A.
N/A.
N/A.
> Update privacy.html.erb - update link

- lib/views/help/requesting.html.erb
We don't need to put the year in brackets in the name of an Act of Parliament. I know that the NHS page we link to does but I don't think that's right. See also: https://www.legislation.gov.uk/ukpga/1990/23/contents
> Update requesting.html.erb - no brackets for year of an Act of Parliament

- lib/alavetelitheme.rb
https://github.com/mysociety/alaveteli/issues/6341
Remove custom autoloaded path
Fixes issues when using theme on Rails 7 as this was causing the post install script to error with:
```
Zeitwerk::NameError: expected file ./lib/censor_rules.rb to define constant CensorRules, but didn't
```
Needed to explicitly require some files as Rails convention is to not autoload files under `lib/`.
See: https://github.com/rails/rails/issues/38671#issuecomment-947449850
> Remove custom autoloaded path

- lib/model_patches.rb
- lib/views/help/officers.html.erb
#454 
Adds text about why we keep requests private to the help pages
We get lots support email from authorities who want to know if they still need to answer requests that they can't see on WDTK
> Add help text about private requests to FOI officer page

- lib/model_patches.rb
Fixes #1579
This adds the `no-reply` email used by the London Borough of Bromley / OneTrust Privacy Portal to the list of invalid reply addresses in `model_patches.rb`
To prevent confusion occurring as messages are being sent from a no-reply email address with no alternate way of replying.
Nothing of note.
N/A
🧁 🍰
> [#1579] Add LB Bromley / OneTrust no-reply email

- lib/views/public_body/_more_info.html.erb
New ways to link to external sites from authority pages and minor changes to help text.
New ways to link to external sites from authority pages and minor changes to help text. 
See above.
N/A.
N/A
I am trying to squash my commits but this may not work.
> New ways to link to external sites from authority pages and minor changes to help text 

- lib/model_patches.rb
Fixes mysociety/whatdotheyknow-theme#1587
This adds a new email address for Microsoft 365 / SharePoint to the invalid reply address list in `model_patches.rb`
Emails are being sent from a new address which we need to suppress, otherwise user replies may go to the wrong recipient.
N/A
This is related to mysociety/whatdotheyknow-theme#1263 - we should retain the existing addresses as they may still get some use.
> [#1587] Add new Sharepoint address to `model_patches.rb`

- lib/model_patches.rb
Allows us to quickly add spam terms to a deployed
`config/spam_terms.txt` file.
> Read custom spam terms from a config file

- lib/model_patches.rb
Fixes #1603
Adds a new email address to the `invalid_reply_addresses` list used by `ReplyToAddressValidator`.
The Metropolitan Police are now replying to some requests from a no-reply mailbox.
Nothing of note.
N/A
Nothing of note here, it's a simple enough change. 😊
> Add Met Police no-reply address to `model_patches.rb`

- lib/model_patches.rb
Fixes #1622
This adds a new address to the `invalid_reply_addresses` list used by `ReplyToAddressValidator`.
Rugby BC are issuing some messages from a no-reply address, so Alaveteli needs to be able to distinguish this so that users can chase up requests.
N/A
N/A
> [#1622] Add no-reply address for Rugby BC to `model_patches.rb`

- app/assets/stylesheets/responsive/custom.scss
- lib/views/general/_frontpage_articles.html.erb
- lib/views/general/_frontpage_extra.html.erb
Fixes: https://github.com/mysociety/whatdotheyknow-theme/issues/1433
A specific of https://github.com/mysociety/whatdotheyknow-theme/issues/791
This PR add article section into the front page:
https://user-images.githubusercontent.com/13790153/209301593-ee455792-cebf-4eb7-b03a-2a4bf8abae2a.mov
@garethrees let me know if you'd like me to change the background colour of this section. It's the same issue that I describe in the [comment for this PR](https://github.com/mysociety/whatdotheyknow-theme/pull/1541#issuecomment-1362510407)
Let me know if you like this solution and if there is any feedback.
> [1433] Added article section in Homepage

- lib/views/public_body/_more_info.html.erb
- Fixes #1631
- relates to #1624
This amends the link we use for the Charity Commission of Northern Ireland (charities tagged `charity:NIC00000`) [^1].
It also adds a link for `charity:exempt`, which points to the [guidance on gov.uk](https://www.gov.uk/government/publications/exempt-charities-cc23/exempt-charities#list-of-exempt-charities)
The CCNI link we use is broken and directs users to a page that isn't very helpful to them.
Secondly, at the moment we don't have a way to display an indicator for _exempt charities_. This reuses existing code to do it cheaply.
Nothing of note - however, I do ponder the regex for exempt. Theoretically, we should match `charity:exempt` and `charity:exempt00000` [^1]. I think this does the trick _as is_.
N/A
Nothing of note.
[^1]: where `00000` is the …
> [#1624, #1631] Fix link for CCNI database, add exempt charities

- lib/helpers/donation_helper.rb
- lib/views/request/describe_notices/_successful.html.erb
- spec/donation_helper_spec.rb
Improve tracking of successful request donations 
Fixes #541
Generates:
```
https://www.mysociety.org/donate?
utm_campaign=successful_request&
utm_content=successful+request+donate+now&
utm_medium=link&
utm_source=whatdotheyknow.com
```
> [#541] Fix donation link

- lib/model_patches.rb
Fixes #1666
Adds an email address for the NHS Business Services Authority (NHSBSA) to `ReplyToAddressValidator.invalid_reply_addresses` in `model_patches.rb`.
NHSBSA issue messages from an email address that does not accept mail.
Nothing to note
N/A
N/A
> Add NHSBSA no-reply email to `model_patches.rb`

- lib/model_patches.rb
Reduce the daily cap on `UserMessages` to combat abuse. It's unlikely that genuine usage exceeds this level.
Requires https://github.com/mysociety/alaveteli/pull/7677
> Add custom `User.content_limits` configuration

- lib/model_patches.rb
Adding Horsham do not reply address
Fixes #1681 
Adds the do not reply address for the council
They are replying to requests from a do not reply address
n/a
n/a
> Add a do not reply address for Horsham District Council

- lib/model_patches.rb
Fixes #1686 
Adds the no-reply email address for Plymouth City Council to `ReplyToAddressValidator.invalid_reply_addresses` in `model_patches.rb`.
Plymouth CC are acknowledging requests from a no-reply mailbox. This has the potential to cause frustration for users, as replies may end up going into the ether.
N/A
N/A
> [#1686] Add Plymouth City Council no-reply

- lib/config/wdtk-routes.rb
- lib/controller_patches.rb
- lib/views/help/_sidebar.html.erb
- lib/views/help/exemptions.html.erb
#1706
Adds a help page about the various FOI and FOISA exemptions, with links to guidance
We had no way of linking users to guidance on specific issues. Help people to understand what they can and can't get released under FOI
> 1706 add a help page on exemptions

- lib/model_patches.rb
https://www.whatdotheyknow.com/request/social_care_systems_and_subject_139#incoming-2323004
I'm pretty certain this is a no-reply address, but I might have got mixed up.
None
> Add North Lincs noreply address to model_patches.rb

- lib/model_patches.rb
Fixes #1700
Adds the no-reply mailbox used by Sandwell MBC in recent responses, to the `invalid_reply_addresses` list used by `ReplyToAddressValidator`.
Sandwell are issuing responses (via Granicus / Firmstep), sent from a mailbox that does not accept replies.
Nothing of note.
N/A
N/A
> Add Sandwell MBC to `model_patches.rb`

- app/assets/stylesheets/responsive/custom.scss
- lib/config/wdtk-routes.rb
- lib/controller_patches.rb
- lib/views/help/authority_performance_tracking.html.erb
Fixes #1172
Adds a help page with the performance tag table on it.
We wanted to be able to publicly link to the tags we use, so we can publicly monitor how widespread an issue is.
N/A
I added some basic styling to the table, but that's entirely optional.
> 1172 publish the tags we use for tracking poor public body performance on the help pages

- lib/views/help/officers.html.erb
- lib/views/help/privacy.cy.html.erb
Fixes #1112 
Fixes the broken ICO links found by @garethrees, tweaks the wording slightly to include the current quote.
The links don't work!
> 1112 broken links to ico guidance in the help pages following ico website changes

- lib/views/general/_responsive_footer.html.erb
Fixes #654 
Adds link to the other landing pages
To better market Pro
The question marks looked ugly, so I switched to the plural instead. Could add "for" in front of these.
> Adding link to role specific pro pages

- lib/config/wdtk-routes.rb
- lib/controller_patches.rb
- lib/views/help/search_engines.html.erb
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/1713
Adds a help page with information about search engine removals on it
It's part of the GDPR template, so good to have it on the site to point people to
n/a
> 1713 add help page on our relationship to search engines

- lib/helper_patches.rb
- lib/views/general/_before_body_end.html.erb
- lib/views/request/show.html.erb
Part of https://github.com/mysociety/sysadmin/issues/1768
- Remove call to old Google Tag Manager experiment.
- Switching to GA4 so needs to replace calls to `ga` with `gtag`.
> Update calls to universal analytics

- .github/workflows/ci.yml
- .github/workflows/mirror.yml
- .github/workflows/rubocop.yml
- README.md
Sync changes made on GitHub back to the mySociety git repo.
> Add mirror GitHub workflow

- .github/workflows/ci.yml
- .github/workflows/rubocop.yml
Add GitHub CI and Rubocop actions
Based on those in core Alaveteli. It would be good to get these running in themes as well to ensure we're deploying with confidence.
> Add GitHub CI and Rubocop actions

- lib/views/general/_frontpage_extra.html.erb
More timely content feels like it should be further up the page, with scrolling giving you the more evergreen content.
> Move the blog up the frontpage

- app/assets/stylesheets/responsive/custom.scss
- lib/views/help/glossary.html.erb
It's a bit disorienting when you're looking for a letter and it's not next to the letter you were expecting because of the jump (e.g. I'm looking for "L", expecting it to be right of "K", but it's actually right of "I"). This PR adds missing letters, styling them with a muted colour so it's obvious there's no entries for that letter.
It also improves the styling, giving each letter a bit more of a target click space, highlights each letter as you focus (if it has entries).
> Improve the glossary nav

- lib/config/wdtk-routes.rb
- lib/controller_patches.rb
- lib/views/help/_sidebar.html.erb
- lib/views/help/about_foisa.html.erb
#11 
Adds a page about the Freedom of Information Scotland Act
We don't have guidance about Scotland on the Site
> [#11] Add FOISA help page

- lib/config/wdtk-routes.rb
- lib/controller_patches.rb
- lib/views/help/_sidebar.html.erb
- lib/views/help/about_foi.html.erb
Fixes #1726 
Creates a barebone FOI page
We didn't have one
Check that <%= select_authority_path %> is the correct place to point people to to make a new request. Also links to the FOISA page that doesn't exist yet, so the link to that may or may not need pulling/changing depending on what happens with https://github.com/mysociety/whatdotheyknow-theme/pull/1725
> 1726 add a help page about the freedom of information act

- lib/views/help/unhappy.html.erb
Fixes #527 
Adds clarity around the need to request an internal review if the authority hasn't responded, points out that the ICO consider complaints where an authority has refused to carry out an internal review. Other minor wording tweaks.
We get support mail about non-responses, and this wasn't as clear as it could be
n/a
n/a
> Add clarity around non responses

- lib/views/help/_contact_form.cy.html.erb
- lib/views/help/_contact_form.html.erb
- lib/views/help/_contact_form_privacy_notice.cy.html.erb
- lib/views/help/_contact_form_privacy_notice.html.erb
- lib/views/help/_contact_volunteer_form.html.erb
#865 
Adds link to Privacy notice to contact forms
There was no link to the privacy notice on the contact form
> 865 add link to privacy notice on contact forms

- lib/views/public_body/_more_info.html.erb
Links from students' unions pages to the parent institution e.g. from University of Lincoln to University of Lincoln Students' Union.
See above.
See above.
See above.
None.
None.
None.
> Links from students' union pages to parent institutions

- lib/config/wdtk-routes.rb
- lib/controller_patches.rb
- lib/views/help/_sidebar.html.erb
- lib/views/help/no_response.html.erb
#1743 
Adds a page on how to appeal to the ICO/OSIC if you've not had any response to your request at all.
Our guidance around this was buried on the unhappy page and a bit limited
I consistently misspell receive, so please check none have snuck in.
> Appealing to the regulator when you haven't had a response at all

- lib/views/help/_sidebar.html.erb
- lib/views/help/unhappy.html.erb
Related to https://github.com/mysociety/whatdotheyknow-theme/issues/1743
Links up the new non-response guidance added in https://github.com/mysociety/whatdotheyknow-theme/pull/1748
Give users the help they need when they're in the specific context
Sidebar:
Link to `/help/no_response` from relevant section on `/help/unhappy`
We might want to consider shortening the guidance on  `/help/unhappy` now that we have the specific page on non-responses, but can tackle that as a separate change.
> Improve non response flow

- app/assets/stylesheets/responsive/custom.scss
https://github.com/mysociety/alaveteli/issues/4504
Makes the correspondence headers sticky so they're always visible as you scroll through the correspondence.
So that when you're reading some correspondence, you can always know if it's incoming or outgoing, who it's from and when it was sent.
Wasn't sure if any bit of this would be in core rather than theme, but seemed to all fit nicely here anyway.
(before I fixed rounded corners)
The rounded corners made it quite a bit more complicated because you don't want to see anything underneath the outside of the rounded corner. If you get rid of the rounded corners, most of it isn't needed.
> Make correspondence headers sticky.

- lib/alavetelitheme.rb
- lib/config/wdtk-routes.rb
- lib/controller_patches.rb
- lib/data_breach.rb
- lib/mailer_patches.rb
- lib/views/contact_mailer/data_breach.text.erb
- lib/views/help/_sidebar.html.erb
- lib/views/help/report_a_data_breach.html.erb
- lib/views/help/report_a_data_breach_thank_you.html.erb
- spec/integration/report_a_data_breach_spec.rb
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/1602
This adds a new help page containing a form for reporting data breaches. When submitted the form is emailed to the site admins.
It follows a similar pattern to the volunteer contact form, that was added in #1208, but uses a new POST endpoint for handling the form submission.
Opening this pull request for feedback and to check that this is heading in the right direction.
There's still a bit more to do on this, namely:
> Add page for reporting data breaches

- lib/views/general/_frontpage_how_it_works.html.erb
Now possible after 15 years!
Looks the same; just links to `/help/about_foi`.
> Link to our own guidance on FOI

- lib/model_patches.rb
Fixes #1763 
Adds the do not reply address that Hillingdon are using
They use a do not reply address
> Add no reply address for Hillingdon

- lib/views/help/requesting.html.erb
fixes #1757 
Adds a line about asking for a set format when you make your request.
We didn't say this before
> Add wording about specifying format at time of making request

- lib/model_patches.rb
Fixes #1769
Adds a noreply address for FCDO
They started sending responses from a noreply address
> Add a no-reply address for FCDO

- app/assets/stylesheets/responsive/custom.scss
Little extra to https://github.com/mysociety/whatdotheyknow-theme/pull/1747 to move the sticky headers down if the admin bar is being shown, rather than being sticky underneath it.
> Move sticky correspondence headers down for admin.

- lib/data_breach.rb
- spec/integration/report_a_data_breach_spec.rb
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/1767
> Set Reply-To for data breach emails.

- lib/views/help/contact.html.erb
While it's linked from the sidebar, it might not be obvious to FOI officers navigating to the contact page (likely via the footer).
> Signpost data breach form

- lib/views/help/volunteers.html.erb
Fixes #1773
This replaces a TODO on `/lib/views/help/volunteers.html.erb`, with a link to the contact form.
Missed TODO on page.
I haven't added an anchor for a specific section of the contact form, since that doesn't feel relevant here.
N/A
> Add contact form link to `/help/volunteers`

- lib/model_patches.rb
Fixes #1785 
Adds the no reply address that York have been using to issue responses
They use a no reply address to issue responses
> Add no reply for city of York council

- lib/views/help/report_a_data_breach.html.erb
Adds basic HTML validation to check that the submitted value looks like a valid email address.
Allows empty values.
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/1792.
> Use email_field for data breach form DPO

- lib/views/admin_public_body_change_requests/add_accepted.text.erb
- lib/views/admin_public_body_change_requests/update_accepted.text.erb
Replaces https://github.com/mysociety/alaveteli/pull/7936
Minor wording changes for new authorities/authorities change emails
This change will reduce admin time editing the default outgoing message when accepting a request to add a new authority.
> Update change request emails copy

- lib/views/help/volunteers.html.erb
Bodies are automatically tagged `missing_email`, so put this in the general volunteering tasks list.
Linked to the blog post instead of the tag for now since the former has clearer instructions.
> Add general volunteering task for finding missing

- lib/data_breach.rb
- spec/integration/report_a_data_breach_spec.rb
Add a unique case reference to the data breach form to prevent incorrect threading by GMail.
Requires https://github.com/mysociety/alaveteli/pull/7967
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/1774
Note that I changed the prefix from "BREACH" to "BR" after the screenshot as "BR" maps more closely to our tracker sheet refs.
> Add a case reference to data breach form

- lib/config/wdtk-routes.rb
- Fixes #1805
- Fixes #1806
Fixes the link for ICO disclosure guidance, and adds an equivalent link for Microsoft.
1. The ICO website had been updated, and the previous link was broken.
2. The Microsoft guidance is referred to by support team, but it is not the easiest to link to. This simplifies things.
Nothing really of note here. I did consider if `microsoft-hidden-data` was too generic, but given it relates to Microsoft Office / Microsoft 365 _specifically_, I think it is OK.
N/A
N/A
> [#1805, #1806] Amend, and add, safe disclosure links

- lib/config/wdtk-routes.rb
- lib/controller_patches.rb
- lib/views/help/_sidebar.html.erb
- lib/views/help/appeals.html.erb
Fixes #1743
Adds a basic help page on appealing to the regulators
We had no information about this step in the appeals process
N/A
I'm not 100% happy with the sidebar link text, so feel free to tweak to something better.
> Ico help page

- lib/helper_patches.rb
Requires https://github.com/mysociety/alaveteli/pull/7961.
> Set custom mySociety Datasette URL

- lib/data_breach.rb
- lib/views/contact_mailer/data_breach.text.erb
- lib/views/help/report_a_data_breach.html.erb
- spec/integration/report_a_data_breach_spec.rb
Fixes #1813 
Depends on https://github.com/mysociety/alaveteli/pull/8074
* Collect breach form submitter email
Signed out:
Signed in:
> [#1813] Breach form submitter contact email

- lib/views/help/requesting.html.erb
Send targeted requests is better than "Don't carpet bomb" for two reasons: (1) it is more accessible language and (2) it is likely to evoke images of violence.
See above.
See above.
See above.
N/A.
See above.
> Send targeted request

- lib/pro_account_bans.rb
- spec/pro_account_bans_spec.rb
Fixes #1841
Fix pro sign ups attempts with blank values
With blank values we can't compare to banned values so return early.
Also ensures values are the same case for all banned fields and the keys can be specified as strings or symbols.
> [#1841] Fix pro sign ups attempts with blank values

- lib/model_patches.rb
Adding due to known issue of escaping ampersands:
https://github.com/mysociety/alaveteli/issues/3465
> Add Bournemouth, Christchurch and Poole Council no reply address

- lib/helper_patches.rb
Depends on https://github.com/mysociety/alaveteli/pull/8213
Fixes https://github.com/mysociety/alaveteli/issues/8211
Use updated core helper to add query string to URL.
> [core#8211] Update GA helper

- lib/model_patches.rb
Fixes #1865
Adds a new email address for the Home Office to the `invalid_reply_addresses` list.
Home Office is issuing some replies from a new no-reply address [^1], and as we already handle theirr existing address, Alaveteli should handle this one too.
Nothing of note, just the usual addition to `ReplyToAddressValidator.invalid_reply_addresses`
N/A
N/A
[^1]: ex: [imsg2642511](https://www.whatdotheyknow.com/admin/incoming_messages/2642511/edit), [imsg2645252](https://www.whatdotheyknow.com/admin/incoming_messages/2645252/edit)
> [#1865] Add new home office address the list of allowed email addresses in the `model_patches.rb`.

- config/refusal_advice/section_38.yml.erb
- config/refusal_advice/section_38_actions.yml.erb
Fixes broken links in s38 guidance to both the s38 guidance itself and the confirm or deny guidance
Fixes the links
The links were broken
n/a
n/a
n/a
> Fixing broken links to ICO guidance

- lib/model_patches.rb
Depends on: https://github.com/mysociety/alaveteli/pull/8258
Exclude schools from batch requests
This previously was done in Alaveteli core for the batch category UI. This will now also exclude schools from the batch authority search.
> Exclude schools from batch requests

- lib/excel_analyzer.rb
This is intended to provide a bit more information on the request thread and hopefully head off some questions to support.
Fixes https://github.com/mysociety/whatdotheyknow-private/issues/305
Provides a custom prominence reason for attachments hidden by the analyzer
Hopefully to reduce queries to support
> [ExcelAnalyzer] Provide a custom prominence reason when hiding

- lib/data_breach.rb
- lib/volunteer_contact_form.rb
> Update method calls to set email headers

- lib/model_patches.rb
Fixes #1882 
Adds the do not reply address for Lisburn & Castlereagh
They used a do not reply, and it bounces.
n/a
n/a
> Add do not reply to model_patches.rb

- lib/excel_analyzer/jobs/pii_badger_job.rb
- lib/excel_analyzer/jobs/republish_or_report_job.rb
- spec/excel_analyzer/jobs/pii_badger_job_spec.rb
- spec/excel_analyzer/jobs/republish_or_report_job_spec.rb
If the attachment doesn't get flagged as containing potential PII there are cases where we're comfortable in republishing the attachment automatically, exceptions are:
1. If XLS with pivot cache - the conversion to XLSX means the pivot cache is lost
2. With named ranges and external links present - the data cached isn't being scanned for PII
3. With a data model present - we can't, at present, scan the data inside this data model.
Fixes https://github.com/mysociety/whatdotheyknow-private/issues/312
> [ExcelAnalyzer] republish attachments automatically

- lib/excel_analyzer.rb
- lib/helper_patches.rb
The ProminenceHelper automatically injects a contact us link into the reason why an object has been hidden. While normally this is okay we want to remove this for files hidden by ExcelAnalyzer to reduce inbox support.
> [ExcelAnalyzer] remove prominence contact us link

- lib/views/help/about.html.erb
- lib/views/help/house_rules.html.erb
- lib/views/help/requesting.html.erb
Closed #1885 
Improves the wording on some of the lower ranked help pages to make it more accessible. 
We used a lot of archaic sentence structures and overly formal language, where this wasn't needed. 
This will need sign-off before merging due to changes in the wording of the site rules, which could have wider implications.
> 1885 improve the language on selected help pages with poor readability

- app/assets/stylesheets/responsive/_mixins.scss
Ensure these button are the same height as primary buttons.
Before (with button hover to show difference):
After:
The remaining difference is sue to the primary button boarder styling:
> Fix button-tertiary styling

- app/assets/stylesheets/responsive/_mixins.scss
- app/assets/stylesheets/responsive/custom.scss
This pull request contains some fixes for accessibility issues found in the WDTK theme.
Fixes part of: #1138 
The rest of the issues, will be fixed on the Alaveteli core.
> Accessibility issues: WDTK

- lib/views/admin_request/hidden_user_explanation/_subject_access_request.text.erb
Fixing link to ICO advice
Fixes #1899 
Updates the link
The old link had been changed to redirect to this one, and the ICO might stop doing that at some point.
N/A
N/A
N/A
> Update _subject_access_request.text.erb to fix link to ICO advice

- lib/views/help/officers.html.erb
- lib/views/public_body/_more_info.html.erb
Adding link to FCA mutuals register on relevant authority pages and additional help text about what happens when an email is sent to a close request thread.
See above.
See above.
Authorities need to be tagged "society:[code]".
N/A.
See above.
> Adding link to FCA mutuals register and additional help text

- lib/alavetelitheme.rb
- lib/authority_only_response_gatekeeper.rb
- lib/model_patches.rb
- spec/authority_only_response_gatekeeper_spec.rb
Patch authority only response gatekeeper
Accept responses to authority only requests from extra addresses which authorities might use. For example no-reply addresses from case management systems which aren't changeable.
Made it so adding other addresses is trivial so volunteers can open PRs for other addresses like they do for `invalid_reply_addresses`
> Patch authority only response gatekeeper

- app/assets/stylesheets/responsive/custom.scss
While working on a blog post I noticed the contrast test of anything using `color_mid_grey` against a light background was failing the contrast test(3.11). No issue has been formally created.
Text using the `$color_mid_grey` variable wasn't passing the contrast test(3.11), even against `#fff`. By using `$color_dark_grey` the contrast test is passing with 5.32. Still gets a muted effect.
> Replaced mid_grey with dark_grey

- lib/views/alaveteli_pro/embargo_mailer/expired_alert.text.erb
- lib/views/alaveteli_pro/embargo_mailer/expiring_alert.text.erb
- lib/views/info_request_batch_mailer/batch_sent.text.erb
- lib/views/notification_mailer/daily_summary.text.erb
Add batch citation promo link to pro mailers 
Fixes https://github.com/mysociety/whatdotheyknow-private/issues/332
Can be reverted in September 2024.
> [#332] Batch citation promo text only

- lib/model_patches.rb
In development occasionally see errors where the original data isn't present, normally when my local ActiveStorage store has been cleared.
We can return nil here and some dev operations (EG. indexing) will then succeed.
> Update RawEmail patch

- app/assets/stylesheets/responsive/custom.scss
[Helen discovered ](https://github.com/mysociety/whatdotheyknow-theme/issues/1920)
Improved contrast for the popup element so it passes contrast text
**Black version**
**Green version**
I get why originally we are using the mySociety green.  but I think the problem with that it rarely looks nice inmediately right next to the other colours, they tend to clash with each other. Assuming using green is important I added a gradient that makes it readable, but probably my least favourite option. I tried a darker version so we can continue using white font text, but it didn't look very nice next to the navbar.
**WDTK Variation**
I created a variation of WDTK primary colour, using the same HUE, unlike the green version I think this one looks more WDTK style. 
Let me know if you have any …
> [WDTK] Popup black version

- app/assets/stylesheets/responsive/_mixins.scss
- app/assets/stylesheets/responsive/_mysoc_footer.scss
- app/assets/stylesheets/responsive/custom.scss
Discovered while working on a blog about accessibility for WDTK
Makes the focus state more obvious for users with visual impairments
https://github.com/user-attachments/assets/d749e787-c6c2-4923-8b26-08342414f27e
> [WDTK] Improved focus state for buttons

- lib/views/help/officers.html.erb
None
Trivial change to add a space at the end of a sentence in the help.
So clearer to read.
Trivial.
Before:
None.
> Add missing space in school working day copy

- lib/views/help/about_foisa.html.erb
- lib/views/help/appeals.html.erb
- lib/views/help/environmental_information.html.erb
- lib/views/help/exemptions.html.erb
- lib/views/help/glossary.html.erb
- lib/views/help/no_response.html.erb
- lib/views/help/requesting.cy.html.erb
- lib/views/help/requesting.html.erb
- lib/views/help/unhappy.html.erb
Fixes #1886
This updates the links in guidance, referring to the Scottish Information Commissioner, from `itspublicknowledge.info`, to `foi.scot`.
As the change was in a related place, I've also updated the ICO link for s37 of FoIA (a80173d1fbaf052a7e1b033dce2d2ef4b6cd2b54).
Scottish Information Commissioner has changed their domain.
We don't render the bare links themselves - so  I won't waste pixels here.
> [#1886] Update links for Scottish Information Commissioner

- lib/helper_patches.rb
- lib/helpers/alaveteli_pro/alternative_price_text_helper.rb
- lib/views/alaveteli_pro/plans/_pricing_tiers.html.erb
Prepending module to the Pro Price helper was causing issues in CI only. We don't actually have to do this as helper modules are all included into the same context via ActionView::Base.
> Refactor loading of theme Pro Price helper

- lib/pro_account_bans.rb
- spec/pro_account_bans_spec.rb
Since Stripe API version upgrade [1] in core this hasn't worked as expected.
This is because of changes to ProAccount#update_stripe_customer required to support the newer API and changes to prevent deprecation warnings.
[1] https://github.com/mysociety/alaveteli/pull/8405
> Fix ProAccountBans module

- lib/views/alaveteli_pro/pages/_legal.html.erb
- lib/views/help/house_rules.html.erb
- lib/views/user/_signup.html.erb
- lib/views/user/rate_limited.html.erb
> Private327 pro terms

- lib/views/help/report_a_data_breach.html.erb
Fixes #1948
Fixes #1948
Update the link to the ICO's guidance on Criminal Offence data in the report-a-breach form.
The ICO have re-organised their website.
Nothing to note, a mere swap-out of links.
* Change the old URL to the new URL in `lib/views/help/report_a_data_breach.html.erb` file.
N/A
N/A
> [#1948] Fix ICO Criminal Offence data link

- lib/views/public_body/_more_info.html.erb
Add UCAS links on authority pages
N/A
Adds a link to UCAS website on each authority page for which there is an UCAS code.
N/A
N/A
N/A
Here is an example URL: https://www.ucas.com/explore/search/providers?query=A60
> Update _more_info.html.erb to support UCAS links

- lib/model_patches.rb
Fixes #1946
This adds two new email addresses to the list of no-reply addresses in `model_patches.rb`
Microsoft OneDrive / SharePoint notifications  from public bodies are coming from some differing addresses, and we don't want user replies going there in error.
Nothing to note
N/A
N/A
> Add additional email addresses for Microsoft notifications

- config/refusal_advice/section_12_actions.yml.erb
Fixes #1951
Corrects link to cost of compliance guidance.
The ICO have re-organised their website.
Nothing to note, a mere swap-out of links.
N/A
Nothing specific; but worth noting this had possibly been broken for a little while. Implementing #1714 would help improve this.
> [#1951] Update ICO advice links in refusal advice section 12 costs

- .github/workflows/ci.yml
- .github/workflows/rubocop.yml
- lib/views/followups/_followup.html.erb
- lib/views/general/_nav_items.html.erb
- lib/views/request_mailer/overdue_alert.text.erb
- lib/views/request_mailer/very_overdue_alert.text.erb
Missed changes in core which we are missing on WDTK.
> Reconcile with core

- lib/views/user/rate_limited.html.erb
Depends on https://github.com/mysociety/alaveteli/pull/8575
Adds Pro rate limited upsell
> [core#8535] Pro rate limit upsell

- lib/config/wdtk-routes.rb
- lib/views/general/_default_footer.text.erb
#1840
This adds a new route, `/donate`, which points toward the WDTK specific donation page.
It also adds the enhanced "please donate" wording, from https://github.com/mysociety/whatdotheyknow-theme/issues/1840#issuecomment-2023092325
Current mailbox signature has a rather cumbersome link, this enables a neater solution.
Additionally, the enhanced "ask" is hopefully more eye catching, within the limit that plaintext email has.
Nothing new here, it's just enhancing what is already in the code.
I'm not sure if this closes #1840 completely, or not, so haven't marked it as such.
> [#1840] Donation link

- lib/views/help/house_rules.cy.html.erb
- lib/views/help/house_rules.html.erb
Fixes #1961
- Fixes broken links to s14 guidance, as ICO have re-organised their website.
- Changes RoAR / SAR guidance links, as whilst not broken, the URL has changed.
ICO have re-organised their website.
N/A
N/A
> [#1961]: Update ICO guidance in house rules

- lib/model_patches.rb
Fixes #1966 
Adds a new no-reply email to the list in `model_patches.rb`, for The Met
They have changed the no-reply address their system uses.
N/A
N/A
> [#1966] Add new no-reply email for The Met

- lib/views/help/complaints.html.erb
- lib/views/help/removing_information.html.erb
#1973 
This corrects a typo (`CESA` should be `CSEA`), and makes some slight changes to the copy, so that it flows a bit better. It also spells out `CSEA`, and references Ofcom with their common name.
The copy was good, but it did not flow very well on user's screens, so it looked a bit like a wall of text (within one!), and there were a couple of typos (ref https://github.com/mysociety/whatdotheyknow-theme/pull/1973#pullrequestreview-2675954881).
Additionally, we referred to Ofcom as "Office of Communications" - we should try and avoid `govspeak` here, and use the more common name.
| From | To |
|:------|:----|
| ![Screenshot showing the original rendering of the #illegal copy on page](https://github.com/user-attachments/assets/1576cb19-b70d-44b3-8510-2d4e0855f5ad) | …
> [#1973] Minor improvements to OSA content

- spec/mailers/request_mailer_spec.rb
In Alaveteli the `old_unclassified_updated` mailer has been removed so this test is failing now. Update the example to another mailer which also renders the custom footer.
> Update test for custom mailer footer

- .github/workflows/ci.yml
- .github/workflows/rubocop.yml
Fixes #1971
Changes the CI, and Rubocop, workflows from `ubuntu-20.04`, to `ubuntu-latest`.
GitHub have depreciated support for runners using `ubuntu-20.04`, and are [removing support on 2025-04-01](https://github.com/actions/runner-images/issues/11101).
This is a straight swap from `ubuntu-20.04`, to `ubuntu-latest`. A couple of the other actions have also been updated (`action-rubocop`, and `checkout`)
N/A
Based on the runners in the Alaveteli repo, `ubuntu-latest` should work here.  I did notice that there is a hardcoded dependency to `ubuntu-focal` packages, which doesn't seem to be in the [Alaveteli CI](https://github.com/mysociety/alaveteli/blob/develop/.github/workflows/ci.yml) - I will add a suggested change for review.
> [#1971] GitHub actions: Ubuntu 20.04 depreciation

- lib/model_patches.rb
Fixes #1969
Adds a new no-reply email to the list in `model_patches.rb`, for Govmetric CaseTracker, used by LB Havering.
Some messages are being issued from a no-reply address, and Alaveteli should be able to recognise this.
Nothing to note
N/A
N/A
> [#1969] Add new no-reply address for CaseTracker

- lib/views/help/house_rules.html.erb
- lib/views/help/how.html.erb
Fixes #1975 
Changes the wording around asking for email addresses.
Increasing admin burden of unredacting pro responses.
n/a
n/a
> 1975 changes to house rules around requesting email addresses

- lib/model_patches.rb
Fixes #1851
Excludes certain types of authorities from batch category picker. 
There are different reasons for different types of authorities. These are summarised below. 
This category can include primary schools as as well as secondary schools. In most cases, it would not make sense to make a batch request to both. Batch requests could also result in an unreasonable burden on primary schools that are relatively small public authorities. This is consistent with the decision taken previously for the 'school' tag.
Relevant tags: academies
Due to the number of further education institutions and their size it was felt that it would not be proportionate to allow batch requests to these institutions because it could result in an unreasonable burden on their resources. This is aligned with the …
> Exclude certain types of authorities from batch category picker

- lib/model_patches.rb
Fixes #1980
Adds a new address, for NHS WLT (2422) to the list of "no reply" addresses.
Recent change to NHSMail, messages to old address (in use until recently) are bouncing. This should stop IRs bouncing back.
N/A
N/A
> [#1980] Add address for NHSWLT to no-reply list

- .github/workflows/rubocop.yml
Can't install the gems due to missing libmagic. This change ensure all packages Alaveteli depends on are installed.
> Fix Rubocop Github action

- lib/excel_analyzer.rb
Makes it clear that we can't say more about what has happened.
fixes #1986 
changes the wording slightly
People have been contacting us and we are not able to help them
n/a
n/a
n/a
> Improve wording when files are hidden

- lib/controller_patches.rb
Censor rule creation results in expiry of all related content. On WhatDoTheyKnow this would cause a major problem. This hacks in a preventative measure. Admins who wish to create a global rule can seek developer assistance until a more robust solution is found.
Tested in browser:
> Prevent global censor rule creation

- lib/views/help/_contact_volunteer_form.html.erb
- lib/views/help/contact.html.erb
- lib/views/help/volunteers.html.erb
Fixes [377](https://github.com/mysociety/whatdotheyknow-private/issues/377) 
Tweaks wording around the purpose of the volunteer form and to clarify that you need to be 18 to join the core team.
Reduce the likelihood of any confusion.
n/a
n/a
> Changes to volunteer contact form

- app/assets/stylesheets/responsive/custom.scss
- lib/views/general/_frontpage_bodies_list.html.erb
- lib/views/request/_select_authority_help.html.erb
No longer makes sense to direct our users to AskTheEU in this way.
> GB no longer in EU

- lib/model_patches.rb
Fixes #1991
Include the no-reply email address for South Ayrshire Council in the list of contact emails.
South Ayrshire  are issuing replies from a `no-reply` email address.
n/a
Change was made automagically by Copilot. All appears to be in order, but please do check 🙏
> [#1991, 1993, #1994] Add no-reply email for Ayrshire Councils (North, and South), and NUH.

- lib/views/public_body/_more_info.html.erb
Fixes #1982 
Adds a link to the ons local stats page
We didn't link to is
n/a
I popped it above mentions in parliament, as it seemed more relevant, but can be relegated if that doesn't make sense.
> Add link to ONS explore local statistics pages

- lib/model_patches.rb
- spec/model_patches_spec.rb
Don't add the `missing_email` tag if the public body is a signpost.
This was causing todo items in the admin general index.
> Update PublicBody missing email auto tagging

- lib/model_patches.rb
Fixes:
```
./alaveteli/lib/themes/whatdotheyknow-theme/lib/model_patches.rb:10: warning: already initialized constant SPAM_TERMS_CONFIG
./alaveteli/lib/themes/whatdotheyknow-theme/lib/model_patches.rb:10: warning: previous definition of SPAM_TERMS_CONFIG was here
```
> Fix warning that constant is already defined

- app/assets/stylesheets/responsive/custom.scss
- lib/views/general/_responsive_footer.html.erb
- lib/views/general/_responsive_header.html.erb
- lib/views/help/_sidebar.html.erb
Fixes: https://github.com/mysociety/sysadmin/issues/2036
Accessibility improvements. Most of the issues found were elements shared across all pages on WDTK.
Improve UX and comply with The Illegal Content Codes of Practice
I used the following tools:
- ARC Toolkit
- axe Devtools
Bear in mind they still display errors, like not being able to check contrast ratios. I checked and we pass all the AA, but they are failing the AAA. Let me know if you'd like me to tackle those. I would basically have to darkened the blue in the navigation bar.
Beside that all the fixes in this commit should fix any navigation issues. The alaveteli issues were fixed here:
https://github.com/mysociety/alaveteli/pull/8675
> Accessibility improvements

- lib/model_patches.rb
Adding do not reply for NHS Fife
Fixes #2009
Adds the address
They send from an address that bounces
n/a
n/a
🙏
> Add NHS Fife address to model_patches.rb

- lib/model_patches.rb
Fixes #2021 
Adds no-reply email addresses for Midlothian Council to `model_patches.rb`
Midlothian are sending out from Firmstep and this is configured to send from a no-reply address.
N/A
N/A
> [#2021] Add Midlothian Council no-reply

- lib/alavetelitheme.rb
- lib/user_check_integration.rb
- spec/usercheck_integration_spec.rb
Depends on https://github.com/mysociety/alaveteli/pull/8753
Add UserCheck.com integration with UserSpamScorer
Check for disposable, risky and invalid MX records for email domains.
> Add UserCheck.com integration with UserSpamScorer

- lib/views/user/_signup.html.erb
We do link to it via the email form note, but that's in reference to sharing your email instead of our general policy. Adding it to the wider small print helps make it super clear.
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/2055.
> [#2055] Clearer link to privacy policy on signup

- app/assets/stylesheets/responsive/_mixins.scss
- app/assets/stylesheets/responsive/custom.scss
- lib/views/request/_incoming_correspondence.html.erb
Fixes: https://github.com/mysociety/whatdotheyknow-theme/issues/2015
The message advices the requester that emails and phone numbers are automatically redacted from responses. This should help reducing the amount of emails that the authorities receive from requesters asking why those details have been redacted.
@gbp 
- Initially I added this conditional`<% if @is_owning_user %>`, but I wonder if we also should include another argument that only display the message if there is a response.
- Ideally we don't want to display the "We work to defend the right to FOI for everyone" message at the same time as the warning message. I have included a conditional `<% if show_donation_button? && !flash[:request_sent] && !@is_owning_user %>`, but this conditional might change depending on the point …
> Added note about masked content to requester

- lib/model_patches.rb
Depends on https://github.com/mysociety/alaveteli/pull/8889
We now have a global listing of webmail providers [1], which is used in various places where we use email address domains to do something.
We can now extract the UK-specific domains from
`PublicBody.excluded_calculated_home_page_domains` to this webmail providers list as they are all domains of that nature. The calculated home page domains list will inherit the customised webmail provider list.
[1] https://github.com/mysociety/alaveteli/commit/c0764b7
> Refactor UK-specific webmail providers
